### ISSUE TITLE
Gnopher hole: Module VS Pkg VS Path VS Dir VS SubPkg VS SubModule VS SubDir VS SubPath ...

### ISSUE THREAD

**Issue by moul** [gnolang/gno#1024]
Topic to discuss during an upcoming deep dive meeting.

To define:
- wording for people/documentation
- wording for implementation (consistancy)

Related discussions:
- https://github.com/gnolang/gno/pull/945

To do:
- [ ] Update #1043

**Comment by moul** [comment]
IMO:
- modules are the unit that defines a collection of packages as a whole that you can publish using `addpkg` (rename to `addmod`?).
- packages is what you import at the end, and you don't care if this is the top-level package of a module or a subpackage, and you also want to publish an import modules/packages that were published under a namespace just for code organization.

**Comment by waymobetta** [comment]
Agreed, I thought this `addpkg` was confusing since the functionality encapsulates more than just packages (ie, realms).

**Comment by moul** [comment]
Uploading a `p/` package with subpaths faces no restrictions since they're self-contained and separate from realms.

However, with `r/` realms, we need to consider the dual perspective of an "independent importable package" within go/gno and the unique realm features like addressing, possible assets, and state management.

Decisions on incorporating Modules (Realms with subpaths) into GnoVM and enabling resource sharing remain pending. Note that `gno.Machine` won't understand Modules, but `vmkeeper` could adapt `gno.Machine`.

Without this feature, expecations may vary and inconsistencies could arise when uploading a realm with subpaths. A temporary solution is to validate and trigger `panic("not yet supported")` in such cases.

**Comment by jefft0** [comment]
After yesterday's discussion, I would expect that a `p/` package is versioned but that an `r/` realm is not. You can import an older version of a `p/` package (using `gno.mod`), but you cannot import an older version of an `r/` realm. (`gno.mod` does not allow `r/` realms. If that is true, then other consequences follow.

**Comment by moul** [comment]
Closing, there is no ongoing action.

You are welcome to continue referring to this issue or reopening it if any uncertainties regarding those names arise again.

**Comment by thehowl** [comment]
> Closing, there is no ongoing action.

I'd argue this is resolved when we have a definitions document with these defined?
