### ISSUE TITLE
gnovm doesn't perform terminating statement analysis

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1086]
Originally discovered by @petar-dambovaliev , re-discovered by me in development of gnochess.

```go
package main

func main() {
	z := y()
	println(z)
}

func y() int {
	x := 9
}
```

This code is invalid Go code, but it is valid Gno at the time being. This results in a cryptic panic:

```
panic running expression main(): interface conversion: gnolang.Stmt is nil, not *gnolang.AssignStmt
```

At the VM level, this is the difference between having a `return x` at the end of `y()` (red) and not having it (green):

![image](https://github.com/gnolang/gno/assets/4681308/fdfdf15a-6810-4d7c-a278-7e3f7e3ad15d)

Key takeaways:

- As a consequence of not having a return statement, the Frame is not popped
- `+v (9 int)` is not done, and as a consequence when defining `z` in `main()`, the value popped is instead `(y func()( int))`.

This leads to the stacks not being effectively synchronised in popping/pushing, and to general corruption of the gnovm state, often leading to panics of various nature (the above is an example of around 3/4 I've seen).

The solution is properly implementing the [Terminating Statement](https://go.dev/ref/spec#Terminating_statements) part of the spec, rejecting at pre-processing any function body which does not end in a terminating statement.

The official implementation for terminating statements seems to be the following: https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/go/types/return.go;l=17

**Comment by ajnavarro** [comment]
@thehowl @moul What do you propose to fix this problem? Shall we add a static analysis phase when interpreting the code? Thanks.

**Comment by thehowl** [comment]
> @thehowl @moul What do you propose to fix this problem? Shall we add a static analysis phase when interpreting the code? Thanks.

My proposal is to add static analysis as a step done in the preprocessor when finishing parsing a function literal or declaration.

**Comment by KemalBekir** [comment]
What do you think about looping through all function statements, if the function is declared to return something and if there is non terminating statement, assert  the function is ending with a return statement?
Looks like this code can be added somewhere here
[https://github.com/gnolang/gno/blob/1c6d184cf8282fc8f3836fb4084adff9b5ab518a/gnovm/pkg/gnolang/preprocess.go#L462](url)

**Comment by petar-dambovaliev** [comment]
> What do you think about looping through all function statements, if the function is declared to return something and if there is non terminating statement, assert the function is ending with a return statement? Looks like this code can be added somewhere here
> 
> https://github.com/gnolang/gno/blob/1c6d184cf8282fc8f3836fb4084adff9b5ab518a/gnovm/pkg/gnolang/preprocess.go#L462

That sounds reasonable.
Keep in mind that this needs to work with function literals as well.
Your algorithm would need to maintain a stack of contexts for nested functions, so 
it can differentiate which return statement refers to which function.

```go
func Foo() {
     a := func() int {
         return 5
     }
}
```
And this PR needs to come with a lot of tests.

**Comment by thehowl** [comment]
> What do you think about looping through all function statements, if the function is declared to return something and if there is non terminating statement, assert the function is ending with a return statement?
> Looks like this code can be added somewhere here

approach/location looks good to me. Do note that whatever happens in FuncDecl should be matched with what happens with FuncLitExpr. Aside from that, looks good. Probably a good idea to iterate from the bottom and check using [the "algorithm" here.](https://go.dev/ref/spec#Terminating_statements)

**Comment by moul** [comment]
SGTM, you should proceed. Thank you.

**Comment by mvertes** [comment]
I agree that the terminating statement analysis proposed here is complying to the Go specification and seems correct in its implementation.

However I'm not sure that is the best response (or at least not sufficient) to the class of errors we want to address here: missing or wrong return statements.

We should have a check of each return statement to be compliant with the function signature (including the special case of pre-declared returned values allowing an empty return), and the detection of a missing return the end of function body.

This check will still be necessary, even if we implement termination analysis.

If we have this check, then termination analysis becomes much less useful, except to catch the possibility of skipping a return if all the previous branches have one, which is just an optimisation.

To me the gain of termination analysis in this context is marginal. I don't know if it is justified in the context of an interpreter.

**Comment by piux2** [comment]
@thehowl 

How did we run and verify the test case, and in which commit?

I ran this test case through file testing in the following commits:

March 1, 2023, commit eabc5c4
December 20, 2023, commit e58316c06
Current master


```

//  return.gno
package main

func main() {
	z := y()
	println(z)
}

func y() int {
	x := 9
}
```


The output is
`
panic: fail on files/return.gno: got unexpected error: main/files/return.gno:6: evalStaticTypeOf() only supports *CallExpr with 1 result, got ()`

This is expected behavior. 

I doubt this PR https://github.com/gnolang/gno/pull/1750 fixed anything in this issue, since this may not be an issue in the VM at the first place.
