### ISSUE TITLE
Missing support for Ledger devices

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#1119]
## Description

Currently, the Gno key client library seemingly contains support for Ledger devices, but in reality the Ledger device discover method is never defined:
https://github.com/gnolang/gno/blob/207d66da9a03cf9f8b03146d439623e9509c162b/tm2/pkg/crypto/ledger/ledger_secp256k1.go#L16-L18

This method being defined is a prerequisite for any Ledger usage, for ex.:
https://github.com/gnolang/gno/blob/207d66da9a03cf9f8b03146d439623e9509c162b/tm2/pkg/crypto/ledger/ledger_secp256k1.go#L71-L75

**Comment by amritkumarj** [comment]
I am working on this!

**Comment by amritkumarj** [comment]
@moul Mostly everything is already implemented just initialization of the `discoverLedger` fn is missing 

As you already know ledger device require a chain specific app to be developed, but as gno is similar to cosmos we can right now use their ledger app too (adena wallet also supports ledger devices and they also use cosmos ledger app)

We also need code to talk with the cosmos ledger app which is already implemented here - https://github.com/cosmos/ledger-cosmos-go

I tried using it and it worked perfectly out of the box with the current gno ledger code (just minor interface change required)

So, should we create a new repo in gnolang organization for this cosmos ledger app interface code?

<img width="756" alt="image" src="https://github.com/gnolang/gno/assets/72156537/15ab8b1f-595f-4b82-be03-d00a58519614">
