### ISSUE TITLE
division by zero panics cannot be recovered

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1148]
running the following program:

```
package main

func main() {
        defer func() {
                println("RECOVER", recover())
        }()
        p := 0
        println(11 / p)
}
```

it panics with `panic running expression main(): runtime error: integer divide by zero`. This is to be expected, however seeing as we have a deferred function with recover, this should ideally be catchable by said function.

**Comment by petar-dambovaliev** [comment]
With further investigation, it seems like this is a more general problem where only explicit panics are handled when the user code has a function call to `panic`.
The implicit panics are not handled.

```go
slice := []int{1, 2, 3}
println(slice[5])
```

And 

```go
make([]int, -1)
```

**Comment by Kouteki** [comment]
Solved by https://github.com/gnolang/gno/pull/3067
