### ISSUE TITLE
mixing untyped (negative) floats and integers in arithmetic sometimes drops the sign

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1152]
I don't want to investigate precisely what happens right now; in any case, these are some equivalent expressions and their output in `gno repl`:

```
println(-3.0 * 1.0 / 2.0) // -1.5
println(-3.0 * 1.0 / 2) // -1.5
println(-3.0 * 1 / 2.0) // -1.5

println(-3 * 1.0 / 2.0) // 1.5
println(-3 * 1.0 / 2) // 1.5
println(-3 * 1 / 2.0) // 1.5
```

It seems that if a division happens between an untyped bigint and an untyped bigdec, the sign is dropped.

**Comment by waymobetta** [comment]
Do we mean **unsigned** here, not **untyped**?

**Comment by thehowl** [comment]
Nope, untyped.

In Go syntax, constant expressions (like `"hello"`, or `2 + 4` -- consider them as any arithmetic/basic operation that doesn't reference a variable) are considered [untyped](https://go.dev/ref/spec#Constants).

That is to say that if we had the variables `x, y, z := -3.0, 1.0, 2.0` (the `.0` serves to make them "floats"), then `x * y / z` works fine, because at that point the values are **typed** into floats, and the expression is handled at the machine level, while an expression like `-3 * 1 / 2.0` requires already some handling at the preprocessor level.

**Comment by waymobetta** [comment]
Right, understood. So upon declaration, type gets inferred but can be incorrect. I was thinking that `bigint` and `bigdec` are already typed.
