### ISSUE TITLE
Amino proto file loses Go doc comments

### ISSUE THREAD

**Issue by jefft0** [gnolang/gno#1157]
Consider this Go struct where the Receiver field has [a comment](https://github.com/gnolang/gno/blob/61f3adaaa758d6c8026cb18e5595b2967469cff2/gnovm/pkg/gnolang/values.go#L623-L625). Amino converts it but the proto message [Receiver field](https://github.com/gnolang/gno/blob/61f3adaaa758d6c8026cb18e5595b2967469cff2/gnovm/pkg/gnolang/gnolang.proto#L80) doesn't have the comment.

I know that Amino uses reflection of the Go struct type which doesn't include comments. But we could use `parser.ParseFile` to get the AST from the source code file, only for the purpose of finding comments. Then amino could copy the doc comment into the proto message.

What do you think? Is it desirable for the proto message output from amino to include field comments? Is there another way to do it?

**Comment by moul** [comment]
I definitely agree with the idea of forwarding comments to `protobuf`. However, I'm not in favor of having amino files with comments that are intended to become `protobuf`-specific behaviors. Instead, I suggest adding new helpers so we can annotate `amino` or maybe comment in a way that makes sense generally, not just for `protobuf`. 

I'm not opposed to having a dedicated `ProtobufExtra` helper. This could be explicit enough and easily skipped by anyone not interested in `protobuf`-specific details. This way, we maintain the general applicability of our comments and annotations, while also providing the option for more `protobuf`-specific details for those who need it.

**Comment by jefft0** [comment]
It looks like amino has support for [field comments](https://github.com/gnolang/gno/blob/61f3adaaa758d6c8026cb18e5595b2967469cff2/tm2/pkg/amino/genproto/types_test.go#L18) in the [P3Field struct](https://github.com/gnolang/gno/blob/61f3adaaa758d6c8026cb18e5595b2967469cff2/tm2/pkg/amino/genproto/types.go#L151). But I don't see any code which sets it (other than tests).

**Comment by jefft0** [comment]
Closing as resolved by PR #1235 .
