### ISSUE TITLE
Gno doc subcommand not able to render local files

### ISSUE THREAD

**Issue by waymobetta** [gnolang/gno#1173]
### Description

When attempting to run `gno doc greeter` on the [gnochess tutorial](https://github.com/gnolang/gnochess/tree/main/tutorial/01_getting_started#getting-started), we are met with an unexpected error message (shown below).

### Your environment

* OS and version
* version of gno
* branch that causes this issue (with the commit hash)

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

```
package greeter // import "gno.land/r/demo/001_getting_started/greeter"

// You did it! You're looking at the documentation for greeter.
package greeter

import (
	"time"
)

// Hello greets s, returning different greetings throughout the day.
func Hello(s string) string {
	n := time.Now()
	v := "The time is " + time.Now().Format("Mon Jan _2 15:04:05.00000 MST 2006") + ".\n\n"
	hour := n.Hour()
	switch {
	default:
		v += "Good night, "
	case hour >= 5 && hour < 12:
		v += "Good morning, "
	case hour >= 12 && hour < 17:
		v += "Good afternoon, "
	case hour >= 17 && hour < 22:
		v += "Good evening, "
	}
	return v + s
}

```

### Actual behaviour

Error message:
`commands/doc: package not found: "." (note: local packages are not yet supported)`

### Logs

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution

If we are providing this functionality within the tutorial then we should ensure that it works correctly

**Comment by thehowl** [comment]
![image](https://github.com/gnolang/gno/assets/4681308/6f8d2a28-c60d-43aa-9e71-f6faa48650c8)

Can't seem to replicate?

**Comment by thehowl** [comment]
I think I get it: you weren't running in the gitpod, but rather in a local copy of your own. The `gno` command is not up-to-date; the error message `note: local packages are not yet supported` has been removed a while ago (as I added support for gno.mod a while back :) )

**Comment by thehowl** [comment]
It's resolved. Make sure to `go install ./gnovm/cmd/gno` from the project root! :grin:
