### ISSUE TITLE
`_test.gnoweb` currently doesn't work (resulting in top-level `make test` not working)

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1222]
This has been untracked for a while. The CI for gnoweb is currently disabled, with the following line:

https://github.com/gnolang/gno/blob/fa8eb7753dc5396144dd4166123234af3a3a4da1/.github/workflows/gnoland.yml#L63

I'm making a PR to make `make test` in gno.land work (by commenting out `_test.gnoweb`). This should be fixed sometime shortly.

**Comment by moul** [comment]
See #1241

**Comment by thehowl** [comment]
Closing as #1241 merged
