### ISSUE TITLE
Add better UX for checking if a Gno address is mathematically valid

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#1298]
## Description

Currently, the way to check if an address is valid in Gno is calling `std.DecodeBech32`. I propose a small addition to the `std` library; a wrapper function around `std.DecodeBech32`. This will make the common operation of checking the validity of an address much nicer from the devX perspective.

**Comment by thehowl** [comment]
`func (Address) Valid() bool` is probably a reasonable API (so it can be checked with `if addr.Valid()` simply)

**Comment by leohhhn** [comment]
@thehowl 

Correct me if I'm wrong, or I am not understanding something correctly, but to me it seems that the issue with that approach is that `DecodeBech32` doesn't exist on the same level as the Address type. DecodeBech32 is defined [here](https://github.com/gnolang/gno/blob/f39cc4622631276bb3a9a0cdb585950d81f497a5/gnovm/stdlibs/stdlibs.go#L481), while the `Address` type is defined at Gno level, [here](https://github.com/gnolang/gno/blob/master/gnovm/stdlibs/std/crypto.gno). The solution I see now is to put the validity check function in the `std` library, right next to `DecodeBech32`.

**Comment by thehowl** [comment]
it is currently that way, but that is changing with #859. after that is merged, we can have it very easily
