### ISSUE TITLE
PebbleDB

### ISSUE THREAD

**Issue by faddat** [gnolang/gno#130]
hi,

I've recently been doing a metric ton of work on databases in cosmos, and that is why I haven't popped up my head around here recently.

I think that we're going to find that PebbleDB is glaringly better than others, and that rocks will perform second best to it. 

The trouble with rocks is that it forces us to use cgo ffi, and as they say, cgo is not go.  

catshark and I have been working on pebbledb support for cosmos here:

https://github.com/osmosis-labs/tm-db/pull/4/files#diff-c80e8d6ab5da73cee445b22b98958c8a9d175f3e0001b29503a6e2983feb179d

Note that I strongly suspect that the current implementation has a bug.

Since I'm aware that Osmosis and many other active chains, like Terra are "trapped" in goleveldb, and that the current overall sentiment is that we should have a single DB so that it is easiest to work with, I would like to suggest that before we jump into a testnet, we make sure that gno can use PebbleDB.

It outperforms all other supported databases, and does not force us to use cgo.

**Comment by thehowl** [comment]
https://github.com/gnolang/gno/issues/1013 as a more complete issue tackling the same problem
