### ISSUE TITLE
Tool for comparing source code of standard libaries between Go and Gno

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1310]
It would be useful to have a tool to do what is described in the title. Right now, when reviewing PRs, I'm comparing the source with Go's using [diffchecker](https://www.diffchecker.com/). I think we can create a simple tool that compares the directories and source code in GOROOT/src and those in GNOROOT/gnovm/stdlibs.

My idea:

- `misc/stdlibs_diff`
- Go executable for generating HTML files showing the diff.
- One HTML file per stdlib package.
- Show entire stdlibs/files we're missing, and entire stdlibs/files that have been added.
- Publish on https://gnolang.github.io/gno/stdlibs/

**Comment by thehowl** [comment]
Yes, I envision it as such: for each standard library, have a statically-generated HTML page showing side-to-side diff comparisons of matching go/gno files in the stdlibs. (ie. strings.go matches the equivalent strings.gno). If they differ by a file (because either of the two misses it entirely), show the entire "missing" source file.

Then, in the future, other possible improvements:

- Also do the diff between the `go doc -short -all` and `gno doc -short -all` of the same standard library, and use it as the first element shown on the page
- Allow for multiple diff options (ie. joined diff, like on GitHub, or expanding collapsed source, ...)
- Preview the changes when somebody makes a PR modifying stdlibs

**Comment by FloRichardAloeCorp** [comment]
I understand. Does code comments count as a diff, and do unit test files count as well?
My first thought is that it doesn't need to be a CLI; a simple executable will do the job, at least for the first version.

**Comment by thehowl** [comment]
> I understand. Does code comments count as a diff, and do unit test files count as well?

Yes and yes.

Ideally: find a system for Gno source code to specify the reference Go source code; and add a dropdown to switch between Go source code versions.

> My first thought is that it doesn't need to be a CLI; a simple executable will do the job, at least for the first version.

Totally. I'd think of an executable that can generate this, maybe with a couple of flags or env variables to specify where to find the Go stdlibs and the Gno stdlibs.

Then, additionally, we should incorporate in our CI pipeline the upload of the statically-generated HTML files containing the diffs.

**Comment by FloRichardAloeCorp** [comment]
Ok, I will work on it.

**Comment by thehowl** [comment]
🎉 

Ping me on Discord on the #gnolang-dev channel if you need any help. (username: morganbaz)

**Comment by FloRichardAloeCorp** [comment]
Hello, I've been thinking about which algorithm to use to detect differences between file contents. I'm considering the Myers Algorithm, essentially the output of git diff, with the original file on the left and the differences on the right. Something that might look like this:
![stdlibs_diff](https://github.com/gnolang/gno/assets/110891350/a60b0549-33d2-4a9f-87a4-d8594a728cd2)

Are you okay with that ?

**Comment by thehowl** [comment]
@FloRichardAloeCorp This works, although for "split view" I was thinking of something closer to what GitHub does (try opening a Pull request's diff, clicking the cog and putting "split view"), so you see the original and deletions on the left, and the changed file with additions on the right.

Any diff will pretty much work for a first version, though. If you think that would require too much work to get the alignment right for instance, let's roll with what you made and iterate later :)

**Comment by thehowl** [comment]
@FloRichardAloeCorp love this!

I'd like the tool to work on entire standard library source trees. Ie. `stdlib-diff --src /usr/lib/go/src --dst /path/to/gno-repo/gnovm/stdlibs`
