### ISSUE TITLE
Doesn't recognize Octal numbers that don't contain an `o`

### ISSUE THREAD

**Issue by notJoon** [gnolang/gno#1322]
## Description

There are two ways to represent octal numbers in Go: as a nunber, like `012345`, and by typing the letter `o` to indicate that value is an octal, like `0o12345`.

However, gnolang only recognizes the latter case.

For example:

```go
package main

import "fmt"

func main() {
	octval := 0o12345
	fmt.Println(octval)
}

// Output:
// 5349
```
In this case, it recognizes the `0o12345` as octal well and prints the result `5349`. But, if changes the code like below, It throws an error.

```go
package main

import "fmt"

func main() {
	octval := 012345. // No `o`
	fmt.Println(octval)
}

// error: invalid integer constant: 012345
// Must print 5349
```

expected behavior:
<img width="1042" alt="go oct" src="https://github.com/gnolang/gno/assets/11853918/4448eac6-4e7c-43ca-b1c5-c615c9027658">

My guess is that this problem will be fixed by modifying the [scanner](https://github.com/gnolang/gno/blob/master/gnovm/pkg/gnolang/scanner.go#L123-L130) file or [op_eval](https://github.com/gnolang/gno/blob/master/gnovm/pkg/gnolang/op_eval.go#L55).

**Comment by thehowl** [comment]
>My guess is that this problem will be fixed by modifying the [scanner](https://github.com/gnolang/gno/blob/master/gnovm/pkg/gnolang/scanner.go#L123-L130) file or [op_eval](https://github.com/gnolang/gno/blob/master/gnovm/pkg/gnolang/op_eval.go#L55).

Yes, if you want to take a stab at it, I suggest changing [this part](https://github.com/gnolang/gno/blob/789f4de1d4940eced86f6311479de0819f3f4b11/gnovm/pkg/gnolang/op_eval.go#L67-L74) of op_eval and making it treat `x.Values` that start with `0` to be octals.
