### ISSUE TITLE
[DOCS] Replace relative paths to documents

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#1354]
## Description

Suggested in https://github.com/gnolang/gno/pull/1351#discussion_r1388750616.

Currently, throughout the documentation relative paths to different documents are used. We should instead switch to using absolute paths, since relative paths are prone to errors during docs development.

**Comment by thehowl** [comment]
How do you make the links work the same if you view the docs on GH or on the docs website, if you have absolute paths?

**Comment by zivkovicmilos** [comment]
@thehowl 

I should clarify here that absolute in this context is `/docs/`, not the actual URL path of the document.
Docusaurus knows how to resolve these things based on the config, and it just looks cleaner inside the MD

**Comment by leohhhn** [comment]
Scrapped this effort because it is not docs framework agnostic.
