### ISSUE TITLE
0 "numeric errors" will be `==` to any error created with `errors.New`

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1376]
```go
package main

import (
	"errors"
	"strconv"
)

type Error int64

func (e Error) Error() string {
	return "error: " + strconv.Itoa(int(e))
}

var errCmp = errors.New("XXXX")

func main() {
	if Error(0) == errCmp {
		println("what the firetruck?")
	}
}

// Output: what the firetruck?
```

Discovered while fixing out bugs for #1290.

If the error is `Error(1)`, it works normally.

A workaround is that of making Error a `struct [ n int64 }`, and its `Error` method a pointer receiver. Weirdly enough, without the pointer receiver it doesn't work still!

**Comment by thehowl** [comment]
The root cause is probably different, related to how we pass around errors as values; but I'm leaving that as a `// TODO` for the undertaker

**Comment by ltzmaxwell** [comment]
Briefly it's because the incorrect type. the vm erroneously treat `Error(0)` and `errCmp` with same type of int64, which is the underlying type of Error, thus the value evaluated as int64 are both 0, that is also why Error(1) works. I opened an issue to discuss this #1424 .
