### ISSUE TITLE
Serve faucet via a reverse proxy. 

### ISSUE THREAD

**Issue by daniel-farina** [gnolang/gno#138]
**Low priority**

I noticed the faucet is exposed directly by Go on port 5050. Would it make sense to serve it behind a reverse proxy on port 80 and just add Cloudflare's SSL to it instead of managing certificates with let's encrypt? If yes, I can provide some commands to setup this quickly.

**Comment by jaekwon** [comment]
I fixed it. thank you for the motivation.
