### ISSUE TITLE
Faucet Error

### ISSUE THREAD

**Issue by enzifiri** [gnolang/gno#1408]
# Faucet Error

#### https://test3.gno.land/faucet

Hello, I encounter the "faucet failed" error when I use the faucet and send a request to my wallet.
wallet address: g1tyljpwgc6d6wxgwdny2g9s9pe9qr4nkrhzhfgl

## The source of the error is located in this repository.

https://github.com/gnolang/gno/blob/3cc5ae8d25ee2211b676c53522fdd5032cd9edf6/cmd/gnofaucet/gnofaucet.go#L279

 
 <h2> Additionally, when I enter the console, I encounter this log: </h2>

 > browser: chrome
 
```
go.min.js:14 Uncaught ReferenceError: hljs is not defined
    at go.min.js:14:2
    at go.min.js:14:33
(anonymous) @ go.min.js:14
(anonymous) @ go.min.js:14
faucet:56 Uncaught TypeError: Cannot read properties of null (reading 'innerHTML')
    at main (faucet:56:60)
    at onload (faucet:11:25)
main @ faucet:56
onload @ faucet:11
```
I am not sure if the source I provided below is up to date, but I can see that the faucet is active and has a balance here. I think the reason for the error must be in the code.

####  https://test3.gno.land/r/gnoland/faucet

**Comment by thehowl** [comment]
Hey, @enzifiri.

Alas, the test3 faucet has been depleted long ago. You can ask for having test tokens sent to you on our [Discord server](https://discord.gg/S8nKUqwkPn). In the upcoming testnet/portal loop testnet, we aim to fix this issue with improvements on our faucet infrastructure and functioning.

As an alternative, you can set up a local environment. There is a [getting started](https://github.com/gnolang/getting-started) tutorial that can show you the rough steps to doing this without requiring you to go through installation; though if you've already installed the gno, gnokey and gnoland CLIs you can go through the steps also on your local machine, setting up the node locally.

Hope that helps. If you need more help, please use our [Discord](https://discord.gg/S8nKUqwkPn) or our [reddit](https://www.reddit.com/r/gnoland).
