### ISSUE TITLE
Critical  Issue: configurable VM parameter could halt the chain.

### ISSUE THREAD

**Issue by piux2** [gnolang/gno#1418]
## Description

https://github.com/gnolang/gno/commit/a8675d30e1b2d658d333c24e4a593eefe6969505#r134400942

VM parameter should instead be remain as hard-coded values, as they were originally,  or specified as parameters in the genesis file. Using it as a config parameter is not appropriate.  It could break consensus and halt the chain.

**Comment by thehowl** [comment]
2c:

- the genesis block should not have a limit on VM cycles (or have it at `1<<63`). seeing the packages and realms we're adding, we're likely to have a very big genesis for adding everything.
- the original GnoChess realm required IIRC ~20M gas for publishing, so in general I think we should change the maxgas per TX/block to be either 50M or 100M.
- regarding your concern, the change by Antonio actually only affects genesis as he stated; the reason for that is that the limit to 10M gas persists in the [ConsensusParams](https://github.com/gnolang/gno/blob/a4c7b860cdff285106873b91452c11987cd385c9/gno.land/cmd/gnoland/start.go#L266)

**Comment by piux2** [comment]
- The maximum CPU cycle for a VM is a property of the Machine struct. The lifecycle of a Machine instance exists only for the duration of each msg_addpkg, msg_call, and msg_send message. The number of genesis transactions does not affect the VM CPU cycle because VM CPU cycles are not shared among transactions and messages.. 


- In the master branch, no VM gas is consumed by the gas meter. The 20M gas you see is expended for store access, transaction size, and signature verification. 


- This CLI configuration parameter is passed to the VM Keeper and is used for every Machine instance.

https://github.com/gnolang/gno/blob/5a0ff553350fb1a6d1c997629a4be87e64f40278/gno.land/pkg/sdk/vm/keeper.go#L58

https://github.com/gnolang/gno/blob/5a0ff553350fb1a6d1c997629a4be87e64f40278/gno.land/pkg/sdk/vm/keeper.go#L199

https://github.com/gnolang/gno/blob/5a0ff553350fb1a6d1c997629a4be87e64f40278/gno.land/pkg/sdk/vm/keeper.go#L274

When the node is started, this flag can be set to any value. Since the maximum VM cycle value may vary between nodes, the results of contract execution could differ. For the same contract execution, some nodes might succeed while others might fail due to reaching the maximum VM cycle limit. The chain might never reach consensus and could halt if  node with no more than 2/3 of the voting power returns the same results for the VM execution.

**Comment by moul** [comment]
Here is the original proposal I made regarding this variable: https://github.com/gnolang/gno/pull/828#pullrequestreview-1433955121

**Comment by moul** [comment]
I believe this issue duplicates another one. I expect all those elements to be configurable as GnoLand start options or in the genesis. However, they should also be subject to change through governance votes or hardcoded in other cases.

**Comment by moul** [comment]
Closing. There is no longer a `maxCycles` parameter (#2993). Other configuration parameters may still have an impact, but the goal is to transfer the relevant ones to the new `params` module (#2920).
