### ISSUE TITLE
Add more references to our subreddit

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1420]
While I think we may eventually want to change our strategy for Gno support -- I think we need to have something similar to StackOverflow in that regard, see https://github.com/gnolang/meetings/issues/38 -- seeing as right now it is the "best" solution we have, I think it should be more prominently [shown in places where we put our communication channels](https://github.com/gnolang/meetings/issues/38). Notably, this is missing from our [website's footer.](https://gno.land/).

**Comment by waymobetta** [comment]
If we add it to our Project board then we can still have visibility, but I'd prefer if possible to keep the [DevRel repo](https://github.com/gnolang/devrels) private until we get out processes further defined.

**Comment by thehowl** [comment]
Closing this issue as we're going in another direction for Q/A anyway.

https://github.com/gnolang/meetings/issues/38
