### ISSUE TITLE
[docs] add support for searching the docs

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#1431]
## Description

Since we utilize Docusaurus as one of the main documentation frameworks, we should add in the option to index / search the documentation.

> [!IMPORTANT]
> **The docs need to be deployed to docs.gno.land, before attempting any of the options below**

For Docusaurus we essentially have 2 options:
- Apply for Algolia's DocSearch program (free for open source projects); this way, Algolia indexes everything for us, and we just utilize their services in the docs
- Host our own DocSearch instance, which crawls and indexes the docs; a bit tedious, but there is a chance we might be rejected by Algolia's program for whatever reason 🤷‍♂️ 

More information can be found [here](https://docusaurus.io/docs/2.x/search).

Please ping @alexiscolin if he has bandwidth once we have search support, to coordinate styling the search window 🙏

**Comment by leohhhn** [comment]
[Related](https://github.com/gnolang/devrel/issues/36)

**Comment by leohhhn** [comment]
Applied for free [Algolia indexing](https://docsearch.algolia.com/docs/who-can-apply/). Waiting on the reply currently.

**Comment by leohhhn** [comment]
Since Algolia is not getting back to us, we can try to utilize @albttx's suggestion: [Meilisearch](https://www.meilisearch.com/docs/learn/getting_started/installation). We would need to set it up on our own fully, if we do not want to pay. 

@albttx would be great if you can look into this once all of the GovGen stuff is complete.

**Comment by zivkovicmilos** [comment]
This was closed by https://github.com/gnolang/docs.gno.land/pull/6 and https://github.com/gnolang/docs.gno.land/pull/5

Thank you @alexiscolin and @albttx 🙏
