### ISSUE TITLE
[docs] add analytics to the docs

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#1432]
## Description

Currently, we do not have any analytics set up for our documentation. In the spirit of privacy, we already utilize Simple Analytics for most of our websites to get a sense for user needs. Having visibility into what users reference the most, or search for the most, will give us feedback on what we should focus on in the docs.

Similar to #1431, **docs should be deployed to docs.gno.land before proceeding**.

Since we utilize Docusaurus as the main documentation framework, we can tie it in with Simple Analytics. Example guide I've stumbled upon:
https://docs.simpleanalytics.com/install-simple-analytics-with-docusaurus

Please ping @moul for setting up the Simple Analytics dashboard, once the Docusaurus plugin integration is complete.

**Comment by moul** [comment]
Simple analytics was already configured, we just need to add the snippet which is always the same for any website:

```html
<!-- 100% privacy-first analytics -->
<script async defer src="https://sa.gno.services/latest.js"></script>
<noscript><img src="https://sa.gno.services/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
```


https://github.com/gnolang/gno/blob/0664846a97a2ebb4f888dbfeb2a45566917b2e60/gno.land/cmd/gnoweb/views/funcs.html#L159C1-L161

**Comment by zivkovicmilos** [comment]
@leohhhn 

Yeah, I saw the issue on the repo as well 🙁 

Let's go with the snippet @moul suggested, should be fine that way without the plugin
