### ISSUE TITLE
Setup "nice" stale PRs' bot

### ISSUE THREAD

**Issue by moul** [gnolang/gno#1445]
https://github.com/actions/stale.

The stale bot should not be aggressive. It should, however, be able to close inactive and old PRs.

How about sending a reminder message after 3 months and then closing the topics after 6 months?

**Comment by zivkovicmilos** [comment]
cc @aeddi

**Comment by aeddi** [comment]
I just opened [a PR](https://github.com/gnolang/gno/pull/2804/files) that sends a simple notification at 3 months and closes it at 6 months. 
Do you want me to do the same for issues? Or set a different timeout for them? Or should we just not automate closing issues at all?

**Comment by Kouteki** [comment]
We have issues that are more calls for discussions. I am fine with them remaining open indefinitely, and possibly close some of them on an individual basis.

**Comment by aeddi** [comment]
The latest settings I added on [the PR](https://github.com/gnolang/gno/pull/2804/files) after chatting with moul are:
- after 90 days without activities, a PR is considered stale
- after 180 days without activities, an issue is considered stale
- If they don’t get any updates in the 90 days following that, they’ll be closed automatically

But I can set up a whitelist to ignore issues or PRs that have a specific label (something like `discussions` for example).
