### ISSUE TITLE
contribs/gnodev: start node even if the package fails to publish

### ISSUE THREAD

**Issue by harry-hov** [gnolang/gno#1447]
Currently, if the gnodev command fails to publish any package, Node fails to start. In my opinion, it should still start the Node even if it fails to publish the package and keep watching/monitoring the given package. It should still be able to hot reload.

Here is an example where a Realm developer will not be able to watch the Realm:

Imagine:
- I'm working on some package, `helloworld`, and it uses `p/avl`.
- Let's say there is some problem in `r/boards` (that exists in the example directory).

In the above scenario, if I run `gnodev path/to/helloworld`, it won't be able to start the Node, saying there is an error in loading `r/boards`, blah blah blah... even if `helloworld` never imports `r/boards`.

PS: Thanks @gfanton for #1386 ❤️

**Comment by gfanton** [comment]
Good point, i've made a PR #1456 to set `SkipFailingGenesisTxs` to `true` by default in the genesis file, do you think it's worth it to make this optional ?
