### ISSUE TITLE
shift operator where first operand is an untyped bigint always results in a bigint

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1462]
```go
package main

func main() {
        x := 11
        y := uint64(1 << x)
        println(y)
}

// panic running expression main(): cannot convert BigintKind to Uint64Kind 
```

The solution is to explicitly convert the first operand to a uint64...

```go
package main

func main() {
	x := 11
	y := uint64(uint64(1) << x)
	println(y)
}

// 2048
```

**Comment by deelawn** [comment]
I'm not sure but on the surface the solution to this may be related to the solution in #1423

**Comment by ltzmaxwell** [comment]
Hi,
I've submitted a fix at #1426.

**Comment by thehowl** [comment]
Let me add an issue related to this. I'll avoid making this a separate issue, mostly because I believe Maxwell's #1426 likely tackles this as well, but I want to publicly document another situation where this creates issues.

Consider the following code:

```go
package main

func main() {
	x := 1024
	p := 10
	if x != 1<<p {
		println("WHAT?")
	}
}
```

This will print `WHAT?`, unexpectedly (Go prints nothing).

Because `x` and `1 << p` are different types (per the issue title, `1 << p` is a Bigint), they are considered different.

Naturally, changing `1` to `int(1)` makes the code work as it should. ;_;

@ltzmaxwell, rest assured I will try to review your PR as soon as possible because tracing down bugs like these destroys my mental sanity.

**Comment by ltzmaxwell** [comment]
Hi Morgan @thehowl, 
        this works:
    
```go
package main

func main() {
	x := 1024
	p := 10
	if x != 1<<p {
		println("WHAT?")
	} else {
		println("nothing")
	}
}

// Output:
// nothing
```

**Comment by thehowl** [comment]
@ltzmaxwell I'm getting `WHAT?` on master :)

Or do you mean on your branch?

**Comment by ltzmaxwell** [comment]
> @ltzmaxwell I'm getting `WHAT?` on master :)
> 
> Or do you mean on your branch?

Oh yes, I mean on my branch. Sorry for the ambiguity.
