### ISSUE TITLE
Create a .github/CODEFACILITATORS file and its system

### ISSUE THREAD

**Issue by moul** [gnolang/gno#1466]
The aim is to utilize CODEOWNERS as the barrier to merging and maintain its current function.

Additionally, we will introduce a new role called facilitators. Their responsibility will be to assist with reviews, but they will not have the ultimate decision-making authority.

We need to create the file `.github/CODEFACILITATORS` since it is not an official file on GitHub. The purpose is to establish a connection with a CI system to automatically assign reviewers to new PRs. Ideally, a bot can be implemented to generate a comment that mentions individuals and explains their role.

In the future, we may consider implementing a round-robin system using this framework. However, for now, the primary objective is to assign individuals without making them the final owners.

Please note that the goal is to assign more CODEOWNERS, so this issue is not a replacement but rather a complementary approach.

**Comment by moul** [comment]
@aeddi

**Comment by Kouteki** [comment]
@moul @aeddi would we be able to utilize CODEFACILITATORS and the GitHub bot for the Review team?

The logic would be:
- If the PR author is NOT from the core team, assign the Review team. They will be the 1st review, and the core team will still need to do a 2nd review in order to merge a PR.
- If the PR author is from the core team, skip the Review team

**Comment by jefft0** [comment]
I like the term "facilitators". In our pilot program, we are using the label "review team" which is confusing. (One contributor thought that removing the "review team" label means that the PR won't be reviewed.) Can we rename the "review team" label to "facilitators"?

**Comment by Kouteki** [comment]
@thehowl looking for your input as well

**Comment by aeddi** [comment]
@Kouteki The idea behind the bot is exactly to set up patterns like this, so technically yes, it should be possible when the bot will be ready to implement the flow you described.

**Comment by thehowl** [comment]
There's been an update here and a move towards the right direction. I'm closing this issue to focus on the efforts in #1007, to be undertaken by @aeddi.

- We now have the "review team" (or review triage team, name TBD) -- see #2890. This kind of matches the function of the CODEFACILITATORS, and is already currently working to help us review the incoming PRs from non-core team contributors.
- We don't need more reviews requested on our PRs, but less. See also #2788.
- The bot in #1007 can help us improve the mechanism of how the review team works, by 1. being able to correctly detect non-core PRs and 2. placing the correct label to request a review from the core team, then have a mechanism to also hand off the PR to core once the review team has looked through it.

@moul, feel free to open if you disagree; but given our bot efforts I don't think we should spend time trying to do this.
