### ISSUE TITLE
gnodev time.Now() values are not preserved on reload

### ISSUE THREAD

**Issue by jefft0** [gnolang/gno#1509]
### Description

In gnodev, the reload operation replays all the transactions. In general this lets the realm functions restore the state. But if some realm functions use `time.Now()` then this returns the (arbitrary) time of reload, not the time of the original transaction. Therefore, reload does not actually restore the state. 
### Your environment

* macOS Ventura 13.6.3
* Go 1.20.7
* Latest gnolang/gno as of posting
* Latest commit: c6097cd83326cae0262b20b1fd7dff9e068caf75

### Steps to reproduce

* Set up the [test1 key for gnokey](https://github.com/gnolang/gno/blob/master/gno.land/cmd/gnofaucet/README.md)
* Install gnodev
* Start gnodev
* Register the test1 user, create a board and post with `CreateThread` as follows:
```
gnokey maketx call -pkgpath "gno.land/r/demo/users" -func "Register" -args "" -args "test_1" -args "Profile description" -gas-fee "10000000ugnot" -gas-wanted "2000000" -send "200000000ugnot" -broadcast -chainid tendermint_test -remote 127.0.0.1:36657 test1
gnokey maketx call -pkgpath "gno.land/r/demo/boards" -func "CreateBoard" -args "myboard" -gas-fee "1000000ugnot" -gas-wanted "5000000" -broadcast -chainid tendermint_test -remote 127.0.0.1:36657 test1
gnokey maketx call -pkgpath "gno.land/r/demo/boards" -func "CreateThread" -gas-fee 1000000ugnot -gas-wanted 5000000 -broadcast -chainid tendermint_test -args "1" -args " mytitle" -args "post at <current UTC time>" -remote "127.0.0.1:36657" test1
```
* View the board at http://127.0.0.1:8888/r/demo/boards:myboard . Note the timestamp on the message.
* Wait 5 minutes. In gnodev, press R to reload

### Expected behaviour

The boards realm [uses `time.Now()`](https://github.com/gfanton/gno/blob/6cabad4f9b09bf4a1e03b27fbc0d666467f2ced6/examples/gno.land/r/demo/boards/post.gno#L52) for the displayed post time.  Reload should restore the realm state including timestamps from `time.Now()`

### Actual behaviour

The timestamps of all message have the time of reload, erasing important information. This is because to reload gnodev resends the transactions where the block time is the current time of reload. This same timestamp is returned by every call to `time.Now()` .

(Related, the boards realm in testnet3 was built by replaying transactions, similarly to gnodev reload. The original message timestamps are erased and are set to the same value "2023-08-18 11:44am UTC". https://test3.gno.land/r/demo/boards:testboard .) 

### Proposed solution

One possible solution: The transaction processing code should have an option to specify the block time. Instead of using a high-level broadcast during replay, gnodev should call the lower-level transaction processing code and supply the correct timestamp of the original transaction. This will be used by `time.Now()`.

Here are the message times before reload:
![Screenshot 2024-01-10 at 10 15 01](https://github.com/gnolang/gno/assets/1999543/8d227bbf-8179-47f0-abba-45a39f1511bd)

Here is where all timestamps are reset after reload:
![Screenshot 2024-01-10 at 10 17 17](https://github.com/gnolang/gno/assets/1999543/624fb6e4-605c-4a6c-b73b-5c1d54be5a90)

### ⚠️ Risks and impact if not fixed

A realm developer can't use gnodev with any realm that relies on `time.Now()`. For example:
* Timestamps on posted messages, or any time-based calculations like "number if messages in the last day".
* There are hacks to avoid using `time.Now()` but they introduce security risks of not having reliable timestamps from the transaction.
* The long-term technique to do realm versioning may also solve this problem by replaying transactions, and so this also needs to be addressed in this case.

**Comment by moul** [comment]
Depends on #1511
