### ISSUE TITLE
docs: Add items to navbar

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#1527]
## Description

This is a proposal to add certain links to the navbar on the documentation:
- Link to gno.land - could be under "Home"
- Link to the playground - could be under "Playground"
- Link to the gno blog - could be "Blog" - this can point to [test3.gno.land blog](https://test3.gno.land/r/gnoland/blog) for now, and we can switch it out for the portal loop blog link once we start using it.

Can we add this?

@alexiscolin @zivkovicmilos

**Comment by alexiscolin** [comment]
@leohhhn  OK I add this to my next prios
