### ISSUE TITLE
Auto deployment of docs not functioning properly

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#1532]
## Description

https://github.com/gnolang/gno/pull/1468 was merged in Jan 12th 5:13PM GMT+1. The changes are reflected on [docs.gno.land](https://docs.gno.land) soon after. 
https://github.com/gnolang/gno/pull/1529 was merged in 7 minutes later, but the changes are not live yet as of writing this.

This makes me think that there is an issue with the automatic deployment - perhaps the changes were too close time-wise? Can we look into this?

**Comment by zivkovicmilos** [comment]
I think the issue is that the autodeploy cancels the building process if there are no changes to the `misc/docusaurus` folder:
![Capture](https://github.com/gnolang/gno/assets/16712663/7e260597-a438-479c-8d67-fadf15a3ec7c)

**Comment by leohhhn** [comment]
This shouldn't be the case; autodeployment should happen if there is any change in the `misc/docusaurus`, or the `docs/` folders. 

@albttx can we update this?

**Comment by albttx** [comment]
Oh, yeah, since `docs/` is `../../` from docusaurus folder, it's not taken, i'll check how to fix that
