### ISSUE TITLE
Erroring related to top-level variables in `p/`

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#1538]
## Description

~Packages under `p/` are not supposed to have top-level variables - they are supposed to be stateless.~ Packages can have top-level variables and they can be initialized, but cannot be later modified.  Erroring related to this is non-existent - modifying these variables will not work as expected. Replicate the following example locally:

In root of Gno repo, run 
```
mkdir examples/gno.land/p/demo/tt
``` 

Add following files:

`p/demo/tt/gno.mod:`
```
module gno.land/p/demo/tt
```

`p/demo/tt/tt.gno:`
```go
package tt

var toplevelvar string

func init() {
	toplevelvar = "initialized"
}

func GetVar() string {
	return toplevelvar
}

func SetVar(arg string) {
	toplevelvar = arg
}

```

- Deployment of this will pass normally when running the chain.
- Calling `GetVar` with `gnokey` will successfully access the variable
``` 
> gnokey maketx call -pkgpath gno.land/p/demo/tt --func GetVar --gas-fee 10000000ugnot --gas-wanted 800000 --broadcast dev  

Enter password.

("initialized" string)
OK!
GAS WANTED: 800000
GAS USED:   67444
```

- Calling `SetVar` will not error in any way, but `toplevelvar` will not be updated:
```
> gnokey maketx call -pkgpath gno.land/p/demo/tt --func SetVar --args "changed" --gas-fee 10000000ugnot --gas-wanted 800000 --broadcast dev

Enter password.

OK!
GAS WANTED: 800000
GAS USED:   70271

> gnokey maketx call -pkgpath gno.land/p/demo/tt --func GetVar --gas-fee 10000000ugnot --gas-wanted 800000 --broadcast dev                           

Enter password.
("initialized" string)
OK!
GAS WANTED: 800000
GAS USED:   70081
```

Not sure if this is a feature or a bug, but we should be clear on erroring related to this, since we are pushing the ["packages are stateless" narrative](https://docs.gno.land/concepts/packages). 

~Also, should we allow for `init()` in `p/`?~

EDIT: Top-level variables in packages is indeed a feature. Packages can define top-level variables and have them initialized in `init()`. However, they are not to be modified, and we do not have erroring related to that, as you can see in the previous CLI block.

**Comment by thehowl** [comment]
I'll tell you something even funnier: you can actually `maketx call` stdlibs! :joy: 

```go
$ gnokey maketx call -broadcast -pkgpath strconv -gas-wanted 10000000 -gas-fee 1000000ugnot -func Itoa -args 11 gentest
Enter password.
("11" string)
OK!
GAS WANTED: 10000000
GAS USED:   77386
```

I think the action here is to restrict `maketx call` to work exclusively on `gno.land/r`. wdyt @moul @jaekwon?

**Comment by leohhhn** [comment]
Closing this as MsgCall only works on realms now, after #2242
