### ISSUE TITLE
`sdk/vm` should perform precompiling and basic validation on `MsgAddPkg`

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1661]
Like it is being done client-side, the precompile check should be performed also server-side. This ensures code is correct for anything that we don't catch right now, including #1086.

**Comment by thehowl** [comment]
@petar-dambovaliev FYI, I made an implementation of this in #1695 which leverages the existing go type checker `go/types` to perform the checks; so it doesn't need to go through the transpilation step, and can catch far more errors than `gofmt` can.

**Comment by petar-dambovaliev** [comment]
> @petar-dambovaliev FYI, I made an implementation of this in #1695 which leverages the existing go type checker `go/types` to perform the checks; so it doesn't need to go through the transpilation step, and can catch far more errors than `gofmt` can.

Then we don't have to do anything on this issue.
