### ISSUE TITLE
feat: `PrevRealm` has the same behavior between `MsgRun` and `MsgCall`

### ISSUE THREAD

**Issue by tbruyelle** [gnolang/gno#1664]
Currently, if `PrevRealm` is called directly in the context of `MsgRun`, it returns the *user realm* instead of the user address as in `MsgCall`.

**Comment by grepsuzette** [comment]
Think that's the case inside filetests.
In my test `PrevRealm().Address` is not the same as `std.TestSetOrigCaller(<addr>)`

**Comment by tbruyelle** [comment]
> Think that's the case inside filetests. In my test `PrevRealm().Address` is not the same as `std.TestSetOrigCaller(<addr>)`

It should be the same if your `PrevRealm()` is directly called by the realm behind your test. If not, I'm interested to see your case, because that can be a bug.
