### ISSUE TITLE
security: is there a bug bounty policy?

### ISSUE THREAD

**Issue by odeke-em** [gnolang/gno#1691]
## Description

Kindly asking if there is a bug bounty and rewards policy for those who audit or find vulnerabilities in this software?

**Comment by thehowl** [comment]
cc @kristovatlas

**Comment by kristovatlas** [comment]
> ## Description
> Kindly asking if there is a bug bounty and rewards policy for those who audit or find vulnerabilities in this software?

Thank you for inquiring. We're still in the process of setting up a paid bounty system. In the meantime, any security issues can be reported to security [at] tendermint [dot] com.
