### ISSUE TITLE
Requesting GNOLAND added to Trustwallet

### ISSUE THREAD

**Issue by iandareen** [gnolang/gno#1692]
Gnoland is a will known project if your a follower of ATOM. This token will shine and more holders if we add this to Trustwallet. Hoping for approve. Have a nice day team and gobless.

**Comment by thehowl** [comment]
This is something we need after launch, is trivial to do and can be done by the community; in an effort to do some issue housekeeping, I'll be closing this as there is no action to be taken for a bunch of time still.
