### ISSUE TITLE
In filetests, PrevRealm().Address is std.GetOrigPkgAddr(), instead of std.TestSetOrigCaller's

### ISSUE THREAD

**Issue by grepsuzette** [gnolang/gno#1704]
A potential bug, based on what @tbruyelle said in #1664 and what I read about `PrevRealm()`.

## Description

Happens with a **filetest**:

***a.gno**
```go
package qwerty

import (
	"std"
)

func Address() std.Address {
	return std.PrevRealm().Addr()
}
```

**a_filetest.gno**
```go
// PKGPATH: gno.land/r/demo/qwerty_test
package qwerty_test

import (
	"std"

	"gno.land/p/demo/testutils"
	qwerty "gno.land/r/demo/qwerty"
)

func main() {
	dude := testutils.TestAddress("dude")
	std.TestSetOrigCaller(dude)
	println(qwerty.Address())
	println(std.GetOrigPkgAddr())
	println(dude)
}

// Output:
```

# Expected
So we print 3 lines: 
```
	println(qwerty.Address())
	println(std.GetOrigPkgAddr())
	println(dude)
```
Would expect `qwerty.Address()` to be equal to `dude`.
But instead, `qwerty.Address()` is equal to `std.GetOrigPkgAddr()`.

---
Note: calling `std.TestSetOrigCaller(dude)` does not help either. `qwerty.Address()` will still return the address of "the filetest realm address" before it got modified to `dude`'s address.

**Comment by grepsuzette** [comment]
In `gno/gnovm/pkg/gnolang/realm.go`, `IsRealmPath(pkgPath)` is true when `pkgPath` has prefix "gno.land/r".

```go
if !gno.IsRealmPath(pkgPath) {
  // simple case.
  pn := gno.NewPackageNode(pkgName, pkgPath, &gno.FileSet{})
  pv := pn.NewPackage()
  store.SetBlockNode(pn)
  store.SetCachePackage(pv)
  m.SetActivePackage(pv)
  n := gno.MustParseFile(path, string(bz)) // "main.gno", string(bz))
  m.RunFiles(n)
  ...
  m.RunMain()
} else {
  // realm case.
  store.SetStrictGo2GnoMapping(true) // in gno.land, natives must be registered.
  gno.DisableDebug()                 // until main call.
  // save package using realm crawl procedure.
  memPkg := &std.MemPackage{
	Name: string(pkgName),
	Path: pkgPath,
	Files: []*std.MemFile{
		{
			Name: "main.gno", // dontcare
			Body: string(bz),
		},
	},
  }
  // run decls and init functions.
  m.RunMemPackage(memPkg, true)
  // reconstruct machine and clear store cache.
  // whether package is realm or not, since non-realm
  // may call realm packages too.
  store.ClearCache()
  m.PreprocessAllFilesAndSaveBlockNodes()
  pv2 := store.GetPackage(pkgPath, false)
  m.SetActivePackage(pv2)
  gno.EnableDebug()
  if rops != "" {
	// clear store.opslog from init function(s),
	// and PreprocessAllFilesAndSaveBlockNodes().
	store.SetLogStoreOps(true) // resets.
  }
  m.RunMain()
}
```
Difference could arise there.

**Comment by grepsuzette** [comment]
**Workaround**

Just use `package main` for your *testfile*, get rid of `// PKGPATH: gno.land/r/demo/qwerty_test`.
Then it behaves normally

**Comment by tbruyelle** [comment]
So yes, you got it. When you add a realm path (something that starts with `gno.land/r/`) in the `// PKGPATH:` directive, you basically turn your filetest into a realm. So logically, `std.PrevRealm()` invoked in qwerty won't return the user, but this filetest realm. That's the expected behavior.

I invite you to add a `z3_filetest.gno` in #1705, identical to `z2_filetest.gno` but with a `// PKGPATH:` directive that turns the filetest into a realm.

**Comment by grepsuzette** [comment]
> I invite you to add a z3_filetest.gno in https://github.com/gnolang/gno/pull/1705, identical to z2_filetest.gno but with a // PKGPATH: directive that turns the filetest into a realm.

Done! Closing here. Thanks for your reply.
