### ISSUE TITLE
GnoDev : Logs hard to read

### ISSUE THREAD

**Issue by DIGIX666** [gnolang/gno#1754]
## Description
![image](https://github.com/gnolang/gno/assets/90353329/5d2151d4-f618-4fee-98ca-45abf6adf29c)

I ran into a few problems when I first discovered GnoDev. I find that the error logs are not easy to read. There are lots of lines that don't interest us. 

It might be interesting to simplify log display 🤷‍♂️

**Comment by leohhhn** [comment]
Hey, @gfanton is working on improving the `gnodev` experience. Thanks for pointing it out - [here is the PR](https://github.com/gnolang/gno/pull/1790) @gfanton is working about.

**Comment by leohhhn** [comment]
Hey @kazai777! Logs should be easier to read now, after https://github.com/gnolang/gno/pull/1790 has been merged. Please reinstall `gnodev`.
