### ISSUE TITLE
Error: name NewBasicNFT not declared, realm grc721

### ISSUE THREAD

**Issue by kazai777** [gnolang/gno#1760]
## Description
 I have this error, if I use `NewBasicNFT()`in my code on play.gno.land

## Log : 
recovered: gno.land/r/nft/kazainft/kazainft.gno:12: name NewBasicNFT not declared
stack:
goroutine 60 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/gnolang/gno/pkgs/sdk.(*BaseApp).runTx.func1()
	/opt/build/pkgs/sdk/baseapp.go:743 +0x2cd
panic({0xc60820, 0xc02021fc00})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/gnolang/gno/pkgs/gnolang.predefineNow.func1()
	/opt/build/pkgs/gnolang/preprocess.go:2827 +0x19c
panic({0xc60820, 0xc02021fc00})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/gnolang/gno/pkgs/gnolang.Preprocess.func2.1()
	/opt/build/pkgs/gnolang/preprocess.go:173 +0x4ae
panic({0xbe56c0, 0xc020f33f00})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/gnolang/gno/pkgs/gnolang.(*StaticBlock).GetPathForName(0xc0012b9360, {0xf72600, 0xc0001ca3f0}, {0xc01aaeca00, 0xb})
	/opt/build/pkgs/gnolang/nodes.go:1576 +0x479
github.com/gnolang/gno/pkgs/gnolang.Preprocess.func2({0xc00ab48200?, 0x2, 0x20}, 0x3, 0x7?, {0xf68810, 0xc021547680?}, 0x3)
	/opt/build/pkgs/gnolang/preprocess.go:1416 +0x2e13
github.com/gnolang/gno/pkgs/gnolang.transcribe(0xc00e467c90, {0xc00ab48200?, 0x2, 0x20}, 0x3, 0xf67b10?, {0xf68810?, 0xc021547680}, 0xc00e467767)
	/opt/build/pkgs/gnolang/transcribe.go:728 +0x4e88
github.com/gnolang/gno/pkgs/gnolang.transcribe(0xc00e467c90, {0xc00ab48200?, 0x1, 0x20}, 0x4b, 0xf68c88?, {0xf67b10?, 0xc0215476e0}, 0xc00e467997)
	/opt/build/pkgs/gnolang/transcribe.go:162 +0xd33
github.com/gnolang/gno/pkgs/gnolang.transcribe(0xc00e467c90, {0xc00ab48200?, 0x0, 0x20}, 0x0, 0x0?, {0xf68c88?, 0xc014e76620}, 0xc00e467bc7)
	/opt/build/pkgs/gnolang/transcribe.go:687 +0x53a5
github.com/gnolang/gno/pkgs/gnolang.Transcribe({0xf68c88?, 0xc014e76620}, 0x0?)
	/opt/build/pkgs/gnolang/transcribe.go:133 +0xbe
github.com/gnolang/gno/pkgs/gnolang.Preprocess({0xf72600, 0xc0001ca3f0}, {0xf70298, 0xc0061b6840}, {0xf68c88?, 0xc014e76620?})
	/opt/build/pkgs/gnolang/preprocess.go:149 +0x2b6
github.com/gnolang/gno/pkgs/gnolang.predefineNow2({0xf72600, 0xc0001ca3f0}, {0xf70298, 0xc0061b6840}, {0xf6ae38?, 0xc014e76620?}, 0x203005?)
	/opt/build/pkgs/gnolang/preprocess.go:2910 +0xc6f
github.com/gnolang/gno/pkgs/gnolang.predefineNow({0xf72600, 0xc0001ca3f0}, {0xf70298, 0xc0061b6840}, {0xf6ae38, 0xc014e76620})
	/opt/build/pkgs/gnolang/preprocess.go:2835 +0x149
github.com/gnolang/gno/pkgs/gnolang.PredefineFileSet({0xf72600, 0xc0001ca3f0}, 0xc0061b7080, 0xc024ccf458)
	/opt/build/pkgs/gnolang/preprocess.go:90 +0x2c7
github.com/gnolang/gno/pkgs/gnolang.(*Machine).runFiles(0xc00ee23e60, {0xc013ca6c48, 0x1, 0x1})
	/opt/build/pkgs/gnolang/machine.go:367 +0x276
github.com/gnolang/gno/pkgs/gnolang.(*Machine).RunFiles(...)
	/opt/build/pkgs/gnolang/machine.go:333
github.com/gnolang/gno/pkgs/gnolang.(*Machine).RunMemPackage(0xc00ee23e60, 0xc01e9c4a00, 0x1)
	/opt/build/pkgs/gnolang/machine.go:190 +0x20d
github.com/gnolang/gno/pkgs/sdk/vm.(*VMKeeper).AddPackage(_, {{0xf62140, 0xc026c52e70}, 0x2, {0xf61b08, 0xc004c467c0}, {0xf622c8, 0xc00bf3c9a0}, {0xc012e9a6d0, 0x5}, ...}, ...)
	/opt/build/pkgs/sdk/vm/keeper.go:163 +0x496
github.com/gnolang/gno/pkgs/sdk/vm.vmHandler.handleMsgAddPackage({_}, {{0xf62140, 0xc026c52e70}, 0x2, {0xf61b08, 0xc004c467c0}, {0xf622c8, 0xc00bf3c9a0}, {0xc012e9a6d0, 0x5}, ...}, ...)
	/opt/build/pkgs/sdk/vm/handler.go:46 +0x2c5
github.com/gnolang/gno/pkgs/sdk/vm.vmHandler.Process({_}, {{0xf62140, 0xc026c52e70}, 0x2, {0xf61b08, 0xc004c467c0}, {0xf622c8, 0xc00bf3c9a0}, {0xc012e9a6d0, 0x5}, ...}, ...)
	/opt/build/pkgs/sdk/vm/handler.go:27 +0x225
github.com/gnolang/gno/pkgs/sdk.(*BaseApp).runMsgs(_, {{0xf62140, 0xc026c52e70}, 0x2, {0xf61b08, 0xc004c467c0}, {0xf622c8, 0xc00bf3c9a0}, {0xc012e9a6d0, 0x5}, ...}, ...)
	/opt/build/pkgs/sdk/baseapp.go:644 +0x42f
github.com/gnolang/gno/pkgs/sdk.(*BaseApp).runTx(0xc0001a4200, 0x2, {0xc01504ca80, 0xa0f, _}, {{0xc012652d20, 0x1, 0x1}, {0x989680, {{0xc009439b35, ...}, ...}}, ...})
	/opt/build/pkgs/sdk/baseapp.go:823 +0x905
github.com/gnolang/gno/pkgs/sdk.(*BaseApp).DeliverTx(0x0?, {{}, {0xc01504ca80?, 0x0?, 0x0?}})
	/opt/build/pkgs/sdk/baseapp.go:580 +0x17d
github.com/gnolang/gno/pkgs/bft/abci/client.(*localClient).DeliverTxAsync(0xc013b76540, {{}, {0xc01504ca80?, 0x0?, 0x0?}})
	/opt/build/pkgs/bft/abci/client/local_client.go:82 +0x103
github.com/gnolang/gno/pkgs/bft/proxy.(*appConnConsensus).DeliverTxAsync(0x0?, {{}, {0xc01504ca80?, 0x0?, 0x0?}})
	/opt/build/pkgs/bft/proxy/app_conn.go:73 +0x26
github.com/gnolang/gno/pkgs/bft/state.execBlockOnProxyApp({0xf630a0, 0xc013b7c0f0}, {0xf65570, 0xc013b636f0}, 0xc0128a7a00, {0xf6aaf0, 0xc000119b40})
	/opt/build/pkgs/bft/state/execution.go:253 +0x8da
github.com/gnolang/gno/pkgs/bft/state.(*BlockExecutor).ApplyBlock(_, {{0xcf4dd0, 0xb}, {0xcf4dd0, 0xb}, {0x0, 0x0}, {0xc013b4faf0, 0x5}, 0x49483, ...}, ...)
	/opt/build/pkgs/bft/state/execution.go:102 +0x115
github.com/gnolang/gno/pkgs/bft/consensus.(*ConsensusState).finalizeCommit(0xc007cc4c00, 0x49484)
	/opt/build/pkgs/bft/consensus/state.go:1348 +0x97e
github.com/gnolang/gno/pkgs/bft/consensus.(*ConsensusState).tryFinalizeCommit(0xc007cc4c00, 0x49484)
	/opt/build/pkgs/bft/consensus/state.go:1276 +0x313
github.com/gnolang/gno/pkgs/bft/consensus.(*ConsensusState).enterCommit.func1()
	/opt/build/pkgs/bft/consensus/state.go:1222 +0x97
github.com/gnolang/gno/pkgs/bft/consensus.(*ConsensusState).enterCommit(0xc007cc4c00, 0x49484, 0x0)
	/opt/build/pkgs/bft/consensus/state.go:1253 +0xb03
github.com/gnolang/gno/pkgs/bft/consensus.(*ConsensusState).addVote(0xc007cc4c00, 0xc00ca7edc0, {0x0, 0x0})
	/opt/build/pkgs/bft/consensus/state.go:1641 +0x913
github.com/gnolang/gno/pkgs/bft/consensus.(*ConsensusState).tryAddVote(0xc007cc4c00, 0x4b4426?, {0x0?, 0xc004a13bf0?})
	/opt/build/pkgs/bft/consensus/state.go:1484 +0x27
github.com/gnolang/gno/pkgs/bft/consensus.(*ConsensusState).handleMsg(0xc007cc4c00, {{0xf5baa0?, 0xc013ca6420?}, {0x0?, 0xedd824610?}})
	/opt/build/pkgs/bft/consensus/state.go:691 +0x3a8
github.com/gnolang/gno/pkgs/bft/consensus.(*ConsensusState).receiveRoutine(0xc007cc4c00, 0x0)
	/opt/build/pkgs/bft/consensus/state.go:650 +0x457
created by github.com/gnolang/gno/pkgs/bft/consensus.(*ConsensusState).OnStart
	/opt/build/pkgs/bft/consensus/state.go:344 +0x4dc

## Code : 
![Screenshot 2024-03-12 at 13 58 14](https://github.com/gnolang/gno/assets/149690535/07df5000-6382-42aa-81ee-aa9738c58cbe)

**Comment by thehowl** [comment]
Hey! Thanks for the bug report.

Unfortunately, `play.gno.land` attempts to publish code on `test3.gno.land`, which currently has a very old version of package `grc721`. You can see the code for test3's implementation on this page: https://test3.gno.land/p/demo/grc/grc721/

As you can see, `igrc721.gno` does not contain `func NewBasicNFT`... However, that's available on newer testnets, including [the portal loop](https://gno.land/p/demo/grc/grc721/) and any local devnet (ie. launching a local node through `gnoland` or `gnodev`).

For now, I recommend working locally; soon ( :tm: ), we'll have ways to obtain tokens to deploy to the portal loop through a faucet.

I'm closing this issue, please do still comment if you have further queries on this issue.
