### ISSUE TITLE
Missing flag in gnofaucet

### ISSUE THREAD

**Issue by DIGIX666** [gnolang/gno#1792]
<img width="654" alt="SCR-20240318-ppez" src="https://github.com/gnolang/gno/assets/90353329/8e5a4ab3-bb30-4bcb-a932-936242578b4f">

I would try whitelist with gnofaucet but I don't have flag `-home`.  Do you say why I don't have that ? 

For finish the test I used `gnodev`.

**Comment by leohhhn** [comment]
Hey, the faucet part of the tutorial you are following will be removed, now that it is possible to deploy to the Portal Loop. Let me get back to you as soon as I am done with refactoring the tutorial :)

**Comment by DIGIX666** [comment]
Oh ok thanks for your feed back :) 

But Kazaï doesn't have same problem. He has a flage `-home` and I think he looking at gnolang/faucet ?
![image](https://github.com/gnolang/gno/assets/90353329/a1fa518d-c962-47f6-aef1-e86bd80a7974)

**Comment by leohhhn** [comment]
@DIGIX666 as you can see in the top corner of the screenshot - Kazai is looking at `gnofaucet` :)

To be clear, the old version of the faucet, which is referenced in the tutorial you are looking at, is [this](https://github.com/gnolang/gno/tree/master/gno.land/cmd/gnofaucet). This version of the faucet will be deprecated and also removed from the tutorial soon. 

[gnolang/faucet](https://github.com/gnolang/faucet) is the new version of the faucet :)

**Comment by DIGIX666** [comment]
<img width="647" alt="SCR-20240319-qlpy" src="https://github.com/gnolang/gno/assets/90353329/1cf6fb02-cb61-481f-ad5f-e60e167babea">

I looking at `gnofaucet` ?

Thanks  for you precision @leohhhn.  I going look your links :)

**Comment by thehowl** [comment]
To be clear, there are three "faucet binaries"

1. `gnofaucet`, old: has flags `-home` and similar, and was in gno.land/cmd/gnofaucet. It's been removed.
2. `gnofaucet`, new: has fewer flags, and is based on `gnolang/faucet`: it's in `contribs/gnofaucet`.
3. `gnolang/faucet`: [this repository](https://github.com/gnolang/faucet), is independent and can be used as a base to build complex faucets

:)
