### ISSUE TITLE
From Zero to Gno.land Hero improvements and Issues

### ISSUE THREAD

**Issue by MalekLahbib** [gnolang/gno#1794]
## Description: After trying the tutorial, here's my modification suggestions:

- Specify to execute `make fclean; go run ./cmd/gnoland start` in gno.land folder

- Delete the gnofaucet part, and suggest to modify the genesis_balances.txt file instead.

-  in the end, change:
   After inserting your package path,... visit https://test3.<your_realm_path>.
   to :
   After inserting your package path, ... visit https://test3.gno.land/<your_realm_path> (Ex: https://test3.gno.land/r/leon/whitelistfactory).

**Comment by leohhhn** [comment]
Hey, I've implemented feedback into the newest version of the tutorial. The tutorial now lives here: https://github.com/leohhhn/gno-fzgh
