### ISSUE TITLE
ufmt doesn't display the unicode emojis correctly

### ISSUE THREAD

**Issue by MalekLahbib** [gnolang/gno#1814]
## Description
I tried to use unicode emojis with ufmt but each time I have athis character: â

here's my code:

![Screenshot from 2024-03-22 17-12-57](https://github.com/gnolang/gno/assets/111009238/55bc535d-06ba-4b8e-a649-eb84fa714e7f)

and here's what's displayed :

![Screenshot from 2024-03-22 17-13-11](https://github.com/gnolang/gno/assets/111009238/496ee570-e8cf-4355-aa47-dbc18b63c92a)

I tried with other unicode emojis and had the same result.

I discussed this with @moul and he explained to me that the problem is the way ufmt.Sprintf works and challenged me to correct the function so that it works with unicode: Challenge accepted!!

PS: give me some time, I'm not that genius :smiley:

**Comment by MalekLahbib** [comment]
I modified ufmt.Sprintf function as @moul suggested, by converting the entry string to [ ]rune, I made some tests and it seems to work correctly now. I pushed to my fork,I have a PR waiting [1811](https://github.com/gnolang/gno/pull/1811).

**Comment by leohhhn** [comment]
Hey @MalekLahbib, have you managed to open a new PR for this since we talked on #1811?

**Comment by notJoon** [comment]
> Hey @MalekLahbib, have you managed to open a new PR for this since we talked on #1811?

If you don't plan to open a PR for this issue, may I handle this if you don't mind?

**Comment by MalekLahbib** [comment]
> > Hey @MalekLahbib, have you managed to open a new PR for this since we talked on #1811?
> 
> If you don't plan to open a PR for this issue, may I handle this if you don't mind?

Hey @notJoon, sorry for the delay of the response, I had some issues on my PC and with git (still a newbee :laughing: ), I made this PR [1889](https://github.com/gnolang/gno/pull/1889), you can take a look and tell me what you think of it.

**Comment by MalekLahbib** [comment]
this issue is supposed to be solved with this PR [1889](https://github.com/gnolang/gno/pull/1889)

**Comment by leohhhn** [comment]
Hey, just a heads up - you always should wait for a PR to be merged before closing an issue. What would happen if the PR is never merged for some reason?
