### ISSUE TITLE
[multinode] Validator set injection through a Realm

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#1823]
## Description

This effort covers the ability for the TM2 consensus mechanism to use the validator set that is specified in a Realm.

Currently, the validator set is kept in-memory (and on-disk), and changes to it are subject to protocol-level changes for mechanisms like PoS. This effort would tackle enabling the consensus layer to utilize a validator set that is abstracted away inside a Realm.

The benefit of having the validator set inside a Realm is the ability to transparently manage it and govern who can be validating and building blocks.

Successful outcome of this effort:
- The validator set is abstracted away from the consensus mechanism in TM2
- The validator set is read from a predeployed Realm

**Comment by moul** [comment]
@zivkovicmilos are you working on it? please call me so we can clarify some details.

**Comment by zivkovicmilos** [comment]
@moul 
I'll start laying the groundwork for it during the week 👀 

I'll ping you about this so we can set up a slot
