### ISSUE TITLE
[chain] Support for on-chain Realm Events

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#1833]
## Description

This effort covers the ability to emit events on-chain through Realm gno code, and being able to parse those events through transaction results.

[Copied from a Gno issue](https://github.com/gnolang/gno/issues/975):
As Gno revolves around Smart Contracts (Realms), there is a need for tapping into real-time Realm data off-chain. For example, a Realm could house the validator set (addresses / public keys) for the running chain.

In order for critical data to be housed on a Realm, it should be reachable from a 3rd party process that potentially lives off-chain. In our validator set example, there should be a listener that can *subscribe* to Realm state changes, and execute node-specific protocol logic accordingly.

Solidity in Ethereum has a similar concept in the form of *Events*. In Solidity, users can specify an *event emit*, which is reflected in the Transaction Receipt as part of the execution log. Based on this log, users can subscribe to ongoing Events and be alerted the moment they are committed to the running chain.

Previously, there was the ability for the Gno node itself to index transactions over RPC (HTTP / WS), but this functionality has since been deprecated.
Based on discussions with [@jaekwon](https://github.com/jaekwon) on on [Gno Event Store PR \(indexing\)](https://github.com/gnolang/gno/pull/546) and [tm2-js-client issue](https://github.com/gnolang/tm2-js-client/issues/46), we've finalized the scope of work that needs to be done in order to provide users with indexing functionality. This scope of work consists of building out a separate tool that is capable of parsing event information from the TM2 node, and internally indexing the data so it can be provided to users. The functionality that this tool should have is not limited to:
* import past transaction data
* monitor new event data
* provide an RPC endpoint (HTTP / WS) for querying indexed data
* provide the ability to subscribe to specific event types

Successful outcome of this effort:
- There exists a standalone tool that can index blocks and transactions, and provide the detailed functionality through RPC endpoints - ✅ done with [tx-indexer](github.com/gnolang/tx-indexer)
- The Gno execution environment saves event emit data in the transaction result, so that it can be indexed and read asynchronously

Related:
- #1653 
- #853
- #575

**Comment by n0izn0iz** [comment]
IMO, events in transactions results should include the path of the realm emitting them

**Comment by zivkovicmilos** [comment]
> IMO, events in transactions results should include the path of the realm emitting them

@notJoon what do you think about this proposal?

**Comment by notJoon** [comment]
> > IMO, events in transactions results should include the path of the realm emitting them
> 
> @notJoon what do you think about this proposal?

I thinks it would be good. This approach could offer several advantages:

1. **Transparency and Traceability**:  By including the path of the realm, we can clearly identify which contract the events are come from. This will help to trace the origins of specific transactions and events.
2. **Provide Context**: Events occurring within a specific realm may be closely linked to particular logic or functions within that realm. Including the realm's path in the event information could aid in interpreting these events more accurately.
3. **Security (maybe?)**: By clarifying the origin of events, I believe we can prevent malicious actors from forging events. 

While there is a tradeoff of increased data size and processing costs exists, but I think the benefits outweigh that.

**Comment by moul** [comment]
Hey, is this issue necessary, or can we merge it with #575?
