### ISSUE TITLE
[infra] Set up a `gnoland` binary release schedule

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#1834]
## Description

This issue concerns creating a CI that will create a release of the `gnoland` binary in some predefined interval, for the purpose of multinode validators pulling it in and running it on their machines.

The CI should create a draft release, and wait for an engineer from the core team to publish it after validation. 
The release should include:
- package deployment to GH Packages
- binary built for different architectures (downloadable archives)
- a change-log detailing what PRs that went into the release

**Comment by 0xMemoryGrinder** [comment]
I am willing to work on this feature. Let me know if I can start soon !

**Comment by zivkovicmilos** [comment]
Hey @0xmemorygrinder, 

We discussed this internally, and ultimately decided to add a foundation for this functionality in #2101 🙏 

Is it possible for you to join us on the Core Contributor calls we host bi-weekly, so we can discuss some tasks you can take up for test4 if you're still interested? 🙂

**Comment by 0xmemorygrinder** [comment]
Hello @zivkovicmilos ,

Sure, how can I join the calls ?

**Comment by zivkovicmilos** [comment]
@michelleellen what are our official links? 👀

**Comment by michelleellen** [comment]
@zivkovicmilos definitely, @0xmemorygrinder would love to have you join, you should be able to add it to your [Google Calendar](https://calendar.google.com/calendar/u/0?cid=Y18xZTVlY2M4NWNhYzY3ZDBiZGE5ZDI3YWRmZjRlOTBiZDMyMjY4ZjI1YTYyMmExZGViODQyMjEwMzllODc4OWEyQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) 

You can share your email and I will add you to the call list too. It is every Wednesday at 5pm CEST. 

We also have a Signal [group](https://signal.group/#CjQKIILslgBotH3nyAkyupxg_0V6ihmYqdP-g_adfahjlbqaEhC--M8xzRrSZjk5WSWfdXOK) if you're interested in joining.

**Comment by 0xmemorygrinder** [comment]
Thanks @michelleellen  for the quick answer, you can send the invitation at 0xmemorygrinder@proton.me
