### ISSUE TITLE
PrevRealm within init() functions in `gno test` is invalid

### ISSUE THREAD

**Issue by n0izn0iz** [gnolang/gno#1852]
### Description

Calling a realm function that calls PrevRealm during init() make PrevRealm return a wrong value

This bug seem to be only present when running `gno test`

### Your environment

* macos 14.2.1
* gno master 55056c58573ec3657b8eb308be83015527386ba7

### Steps to reproduce

Execute `gno test ./examples/gno.land/r/demo/teritori/caller` in [this branch](https://github.com/gnolang/gno/pull/1851)

### Expected behaviour

PrevRealm returns the actual previous realm in init() function in the `gno test` environment

### Actual behaviour

PrevRealm returns an EOA

### Logs

```
❯ gno test ./examples/gno.land/r/demo/teritori/caller                                                                                                                               Native
--- FAIL: TestInitPkgPath (0.00s)
caller should be 'gno.land/r/demo/teritori/caller', but got ''
--- FAIL: TestInitAddr (0.00s)
caller address should be 'g1r2h3mkm8ky54w60vphvk8q7uk36uyum9gsqyj3', but got 'g1wymu47drhr0kuq2098m792lytgtj2nyx77yrsm'
./examples/gno.land/r/demo/teritori/caller: test pkg: failed: "TestInitPkgPath"; failed: "TestInitAddr"
FAIL
FAIL    ./examples/gno.land/r/demo/teritori/caller 	0.54s
FAIL
FAIL
FAIL: 0 build errors, 1 test errors
```

### Proposed solution

Fix PrevRealm behavior in `gno test`'s realms' init() functions

**Comment by leohhhn** [comment]
@n0izn0iz 

The Gno machine that is being used for `gno test` has a hardcoded context. The test machine context is defined [here](https://github.com/gnolang/gno/blob/55056c58573ec3657b8eb308be83015527386ba7/gnovm/tests/file.go#L43). 

There are also some other issues, such as the banker not working as expected in `gno test`.

`gno test` is very clunky and definitely needs to be fixed. Thank you for reporting this issue 🙏

**Comment by n0izn0iz** [comment]
seems fixed on latest master :)

**Comment by thehowl** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHFxZmc0dTM5NXZhZ2x3NzBoaDByZWd0dm9keXlyeHR6b3B0dzJ3ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/yJFeycRK2DB4c/giphy.gif)

**Comment by n0izn0iz** [comment]
actually I just saw this reapear
