### ISSUE TITLE
[GnoVM] Top-level error does not revert state

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#1864]
## Description

If a top-level call in Gno returns an error to the user, the state does not get reverted back to what it was before the transaction. This is counterintuitive and @zivkovicmilos & I believe it will cause confusion down the line. 

If we implement top-level error reverts, there would be two ways to revert tx execution in Gno:
- top-level function returns an error
- a function somewhere in the call stack panics. 

Here is some example code in the playground to showcase the current state of code: https://play.gno.land/p/ENkk-0bq3s6

cc @zivkovicmilos @petar-dambovaliev

**Comment by deelawn** [comment]
I'm very skeptical that state should be reverted when an error is returned from a top level realm function; it seems inconsistent with go's behavior.  For example, if I modify a value in go that exists in a scope outside of the function from which it is modified, I would expect that value to be persisted regardless of whether or not the function that modified it later returns an error.  Returning an error usually means that the operation could not be fully completed as intended and any state modifications outside the scope of the function that returned the error will remain. Panicking means something went horribly wrong and we need to get rid of all state unless the panic is recovered.  It seems like the current implementation most closely aligns with how the terms are used in go.

**Comment by ajnavarro** [comment]
IMO any panic should not commit the state. It should work as a database. Users can choose what to do using error handling.

**Comment by ajnavarro** [comment]
I'm with @deelawn here for several reasons:
- Consistency: rollback only when returning an error on top-level methods but not on the rest is not consistent. It might mislead users.
- Unexpected: as @delawn said, is not consistent with Go behavior.
- Limiting choices: We already have a way to roll back the Realm state, that is, throwing a panic. I can see use cases where a Realm's dev wants to return an error without rollbacking the whole state, like when saving some metadata about who voted, or metrics about the amount of people that used the Realm, as examples.

**Comment by petar-dambovaliev** [comment]
Errors are just values, they have no special semantics within the language. Panic, on the other hand, is special and does what you suggested. This proposal is basically to make errors be treated as panics. I am against.

**Comment by leohhhn** [comment]
Okay. got it. Documentation already states that `panics` revert state, but I will make sure to add mentions and examples of errors _not_ reverting state, which might be what blockchain developers could expect. Thanks.

**Comment by leohhhn** [comment]
Coming back to this after another discussion with the team:
- we'll keep the current behavior of top-level errors not reverting state
- we'll consider adding a check in the simulate phase to tell users if a TX might return an error so they can choose to execute it or not
- we'll watch what developers do down the line with errors vs panics in their code and revisit this topic if needed
and we should make sure that Gnoscan and other UIs notify the user if a transaction returned an error, even if it was technically "successful"
- we'll promote more panics in top level realm functions (returning errors in these cases should be done with clear intent on why errors, and not panics instead)
