### ISSUE TITLE
[chain] Add the `gnoland init` command

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#1885]
## Description

Master issue: #1836 

This issue concerns adding support for the `gnoland init` subcommand, which runs the following commands under the hood:
- `gnoland config init` - default values
- `gnoland secrets init` - default values

It should initialize the node working directory, along with default `secrets` and `config` values.

Blocked by #1882

**Comment by r3v4s** [comment]
Is this going to be replacement for `gnoland start -skip-start=true` ??

**Comment by zivkovicmilos** [comment]
> Is this going to be replacement for `gnoland start -skip-start=true` ??

Yes, it's meant to replace that flag functionality

**Comment by zivkovicmilos** [comment]
@r3v4s 
Starting to work on this now 😎
