### ISSUE TITLE
[gnodev] Accounts with premined balances

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#1935]
## Description

Currently, the only account with a premined balance with `gnodev` is test1. Because of this, it's a bit complicated to get coins on your own keypair that is not test1. 

As a UX improvement, `gnodev` should try to find the local gnokey keybase, and premine balances to all keypairs found in there. This would ease the UX quite a bit. 

cc @gfanton

**Comment by zivkovicmilos** [comment]
Closed with #1938
