### ISSUE TITLE
Incorrect Timestamps in Gno Chains

### ISSUE THREAD

**Issue by adr-sk** [gnolang/gno#1950]
The timestamps in blocks are 2~3 minutes behind the actual time.

This bug affects apps that rely on timestamps to display the transaction/block time.

(e.g. Once you send a transaction and immediately check the history in the app, it will display "2 mins ago" instead of "n seconds ago")

In the video below, I send a transaction on `Test3` in Adena to stimulate a new block and compare its timestamp with the actual time.

- The actual time in which the tx was executed: `09:00:30`
- The timestamp of the block including the tx ([`height 353208`](https://rpc.test3.gno.land/block?height=353208)): `08:58:45`

https://www.loom.com/share/7b1034678a794bedafa72f2d54b93229?sid=3e223cec-b021-4c66-8ac9-6ec584fd693e

Not sure what's causing the discrepancy here, but it's also happening to a custom Gno Chain that we've spun up to develop GnoSwap.

cc @zivkovicmilos @r3v4s

**Comment by moul** [comment]
I've just setup ntpd on test3's node:

```console
root@test3:~# date
Sun 21 Apr 2024 07:52:02 PM UTC
root@test3:~# ntpd
root@test3:~# date
Sun 21 Apr 2024 07:53:28 PM UTC
root@test3:~#
```

Can you check again?

**Comment by adr-sk** [comment]
@moul Seems like the gap's been reduced to 10~20 seconds.

https://www.loom.com/share/507f77eb80de48738545bc3ce3b75ea0?sid=0b3c282d-cc8b-4d2d-a78f-6c752330cf9d

Was `ntpd` already set up for the Portal Loop's node? I wonder why the gap was much bigger in `Test3`.

Also, would it make sense to include a section in the [WIP Multinode Docs](https://github.com/gnolang/gno/issues/1820) that recommends the validator nodes to install `ntpd` on their machines to ensure we don't end up with blocks with "inconsistent" timestamps? (related to our ongoing documentation efforts [here](https://github.com/gnolang/gno/issues/1820#issuecomment-2056779316))

**Comment by moul** [comment]
The real issue is that I'm not sure what happens if a validator provides an incorrect timestamp. 

I think we should implement some checks in the first round of consensus to verify that the suggested timestamp is correct. It should at least be "after the previous block" and not too far in the past or future.

The question is wether we should care about fixing it before the launch or not.

**Comment by r3v4s** [comment]
@moul 
>  if a validator provides an incorrect timestamp.

Is this even possible?? AFAIK, gno's returns timestamp from block(object that gets finalized), not running node it-self.

@zivkovicmilos @thehowl Could you please check if it is manipulatable??

**Comment by n0izn0iz** [comment]
Not sure if this is related but tendermint1 chains had a similar problem, the fix implemented in cometbft is described here https://docs.cometbft.com/v1.0/explanation/core/proposer-based-timestamps

**Comment by aeddi** [comment]
We read several documents and issues on the topic, then we discussed the idea of replacing the calculation of the median time with a mix of:
- Using the proposer’s timestamp
- Checking if the timestamp of the new block is more recent than the previous one
- Checking if the timestamp of the new block is not in the future (with a tolerance of a few seconds)

However, given the complexity of the subject (even just to test and make a decision) and the ongoing issues for the mainnet launch, we decided to keep the implementation as it is.
