### ISSUE TITLE
`Machine.String()` hangs the VM on error when printing large structure

### ISSUE THREAD

**Issue by jefft0** [gnolang/gno#1981]
### Description

If a transaction fails, for example running out of gas, the VM prints the state with `Machine.String()` . If the state has a large recursive structure, like an avl.Tree(), this can hang the VM as it constructs the string. Please see [the analysis here](https://github.com/gnolang/gno/pull/1736).

### Your environment

* The latest gno as of 2024-04-25
* master branch 688edf5deccd68b99a5f2c9ff416b95738938a6f

### Steps to reproduce

Please see PR #1736 which has a txtar to reproduce the bug and has analysis of the root cause.

### Expected behaviour

On error, the VM should print a useful error message.

### Actual behaviour

The VM attempts to dump the entire machine state, even if there is a large recursive data structure.

### Proposed solution

[This comment](https://github.com/gnolang/gno/pull/1736#issuecomment-2013188164) proposes to "switch from doing `Machine.String()` to printing a stacktrace. (This is likely to be more useful and parseable information by the programmer anyway.)"

**Comment by petar-dambovaliev** [comment]
I agree with the solution from @thehowl. Since he is working on it already, i'll take this opportunity to improve the `String()` method on the `Machine` struct because it looks very rugged.

**Comment by thehowl** [comment]
@petar-dambovaliev BTW I haven't taken up on it, I troubleshot the issue because I was pointed at it, but the actual implementation of the stacktraces will take quite some work

You're welcome to take up on this if you want to

**Comment by jefft0** [comment]
In a dev call, it was suggested that https://github.com/gnolang/gno/pull/1994 could fix this issue. It does not. The test still hangs in the txtar of https://github.com/gnolang/gno/pull/1736 .

**Comment by jefft0** [comment]
Closing this tracking issue to focus on the PR with the txtar that demonstrates the bug. https://github.com/gnolang/gno/pull/1736
