### ISSUE TITLE
Document gnoland, gnokey and gnodev commands

### ISSUE THREAD

**Issue by Kouteki** [gnolang/gno#1987]
As a Gno.land user ISBAT see all the available commands in the documentation and how I can utilize them so that I could accomplish my objective.

Acceptance criteria:

1. Review PR #1985 to understand the format needed for the documentation. Use it as a template for this task
2. Sync with Onbloc on their effort to document `gnoland` commands
3. Document `gnoland` commands OR help Onbloc document them on their own
4. Document `gnokey` commands
5. Document `gnodev` commands

**Comment by thehowl** [comment]
FWIW, documentation should go on docs.gno.land, but there should be enough self-help also in the `--help` outputs; maybe one which does a bit less hand-holding and is more succinct

**Comment by leohhhn** [comment]
Hey, about this issue - right now we already have docs on all of the tools ([Gno Tooling section](https://docs.gno.land/gno-tooling/)), albeit:
- gnoland command is a bit outdated and @zivkovicmilos is working on a rewrite
- gnodev should be up to date, recently updated
- gnokey - I took a look, and its mainly missing some of the new features, like MsgRun

What exactly do you think should be added?

**Comment by Kouteki** [comment]
> FWIW, documentation should go on docs.gno.land, but there should be enough self-help also in the `--help` outputs; maybe one which does a bit less hand-holding and is more succinct

@thehowl just to be clear: your proposed improvement is enabling you to hit  `--help` and get all the available parameters, instead of just a small subset currently shown?

**Comment by Kouteki** [comment]
@leohhhn I updated the description to be more specific. Let me know if you need additional clarification.

**Comment by leohhhn** [comment]
As discussed with @Kouteki, the action steps on this issue will be as follows:
- Review [gnokey page](https://docs.gno.land/gno-tooling/cli/gno-tooling-gnokey/)
- Review [gnoland page](https://docs.gno.land/gno-tooling/cli/gno-tooling-gnoland/)
- Review [Working with keypairs](https://docs.gno.land/getting-started/local-setup/working-with-key-pairs) page

And update missing/outdated things accordingly. 

`gnodev` will have its place in the documentation in the Getting Started section [with this PR](https://github.com/gnolang/gno/pull/1936), which should cover the "tutorial" part for it, and `gnokey` already has a section for it (Working with keypairs).

**Comment by zivkovicmilos** [comment]
> As discussed with @Kouteki, the action steps on this issue will be as follows:
> 
> * Review [gnokey page](https://docs.gno.land/gno-tooling/cli/gno-tooling-gnokey/)
> * Review [gnoland page](https://docs.gno.land/gno-tooling/cli/gno-tooling-gnoland/)
> * Review [Working with keypairs](https://docs.gno.land/getting-started/local-setup/working-with-key-pairs) page
> 
> And update missing/outdated things accordingly.
> 
> `gnodev` will have its place in the documentation in the Getting Started section [with this PR](https://github.com/gnolang/gno/pull/1936), which should cover the "tutorial" part for it, and `gnokey` already has a section for it (Working with keypairs).

@leohhhn 

The task is not just to review the existing pages, but to generate completely new documentation on how these tools are used, and under which circumstances they are used.
Please make sure we add meat into the docs for these tools, not just terminal copypastas

**Comment by Kouteki** [comment]
To clarify:

Our objective in this issue is to build learning oriented, tutorial style documentation. This documentation is part of the [Getting Started section](https://docs.gno.land/getting-started/).

1. We need to create Gnokey & gnoland pages in the Getting Started section, and write tutorials that cover use cases and steps. We also need to cover subcommands.
2. We also need to update the existing Working with keypairs page. The format is good, the content needs to be reviewed and all the missing subcommands need to be added.

**Comment by Kouteki** [comment]
I've split the issue into more manageable pieces, closing this one.
