### ISSUE TITLE
[chain] Populate `func` field in emitted events

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#2001]
## Description

This task concerns populating the `func` field (function name) for the emitted events following #1653.

Copying the discussion from the PR:

@moul:
>The func field is empty, and should not, I think we should take the most recent "named" frame.

@notJoon:
>In the second case, where the function name is empty, it seems that the function name cannot be retrieved from the stack frame only for special purpose functions such as anonymous functions (or lambda functions) used in callbacks or defer, or test functions.

cc @Kouteki

**Comment by r3v4s** [comment]
#2160 PR iterates more previous frame than current, to handle func name.

**Comment by zivkovicmilos** [comment]
Closed by #2160
