### ISSUE TITLE
[chain] Add `prev_realm` to emitted events

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#2002]
## Description

This task concerns adding a `prev_realm` field to the emitted events following #1653.

Copied over from the PR:

@moul:
>Consider adding a default field prev_realm to indicate the caller. This helps differentiate it from pkg_path and func, which pertain to the code defining the std.Emit implementation (great). The purpose is similar to assigning assets and bankers to prevRealm instead of origCall or the called contract in synchronous calls.

@notJoon:
>For the last third case, it seems that it can be handled by creating a getPrevRealm function, similar to the function name searcher. It can be done in a way like this:

```go
// Pseudo code for previous realm name getter
func getPrevRealm(m *gno.Machine, height int) (address string, pkgPath string) {
    var (
        ctx           = m.Context.(ExecContext)
        currentCaller crypto.Bech32Address
        // Keeps track of the number of times currentCaller has changed.
        changes int
    )

    for i := m.NumFrames() - 1; i > 0; i-- {
        fr := m.Frames[i]
        if fr.LastPackage == nil || !fr.LastPackage.IsRealm() {
            continue
        }

        // LastPackage is a realm. Get caller and pkgPath, and compare against
        // current* values.
        caller := fr.LastPackage.GetPkgAddr().Bech32()
        pkgPath := fr.LastPackage.PkgPath
        if caller != currentCaller {
            currentCaller = caller
            changes++
            if changes == height + 1 {
                return string(caller), pkgPath
            }
        }
    }

    // Fallback case: return OrigCaller.
    return string(ctx.OrigCaller), ""
}
```
>receiving height as an argument and returning the (height + 1)th change. I think it would be good to gather people's opinions and include the necessary data.

cc @Kouteki

**Comment by r3v4s** [comment]
We should also add 'std.GetOrigCaller' to differentiate it.
