### ISSUE TITLE
[docs] Add documentation for Event / Emit

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#2003]
## Description

This task concerns adding detailed documentation, usage examples and tutorials for utilizing the newly added event emissions, following #1653.

cc @Kouteki

**Comment by leohhhn** [comment]
I've identified three spots where we should add Event/Emit documentation:
- stdlibs Concepts & Reference pages
- Effective Gno, to show examples
- Gno by Example - to have a practical tutorial on how to use it.

Will work on it ASAP.
