### ISSUE TITLE
cannot use non-empty(comparable) struct as key of a map

### ISSUE THREAD

**Issue by ltzmaxwell** [gnolang/gno#2041]
see 
```go
package main

type S struct {
	x int
}

func main() {
	m := make(map[S]string)
	m[S{x: 0}] = "test"
	println(m)
}
```
this compiles in Go but not in Gno, with error msg:
// Error:
// FieldType is a pseudotype with no elements

**Comment by omarsy** [comment]
I'm looking into it. Maybe I have a PR for that
