### ISSUE TITLE
[GnoVM] Deprecate & remove `std.CurrentRealmPath()`

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#2045]
## Description

Deprecate & remove `std.CurrentRealmPath()` in favor of `CurrentRealm().Path()`, as suggested [here](https://github.com/gnolang/gno/pull/1469#discussion_r1555645625). After removing the function from the `stdlibs`, also please remove its references from the docs.

**Comment by linhpn99** [comment]
> @linhpn99 go ahead!

@thehowl @leohhhn https://github.com/gnolang/gno/issues/2045 please take a look
