### ISSUE TITLE
`recover` not working correctly with runtime panics in Gnolang

### ISSUE THREAD

**Issue by omarsy** [gnolang/gno#2146]
#### Description:
The `recover` function does not seem to handle runtime panics correctly in Gnolang, whereas the following code works fine in Golang.

#### Steps to Reproduce:
1. Create and run the following code in Go. The program completes without panic due to the `recover`.

```go
package main

func p() {
	defer func() {
		recover()
	}()
	i := 0
	i = 1 / i
}

func main() {
	p()
}
```
```go
package main

type s struct {
	el func()
}

func p() {
	var el *s
	defer func() {
		recover()
	}()
	el.el()
}

func main() {
	p()
}
```

2. Transpose the same code to Gnolang and run it.

```go
package main

func p() {
	defer func() {
		recover()
	}()
	i := 0
	i = 1 / i
}

func main() {
	p()
}
```
```go
package main

type s struct {
	el func()
}

func p() {
	var el *s
	defer func() {
		recover()
	}()
	el.el()
}

func main() {
	p()
}
```
#### Expected Behavior:
The program should terminate normally without panicking because the `recover` in the deferred function should catch the panic caused by division by zero or use of nil pointer...

#### Actual Behavior:
In Gnolang, the program does not seem to handle the runtime panic, causing the program to crash.

**Comment by thehowl** [comment]
Duplicate #1148
