### ISSUE TITLE
Invalid commands in /r/demo/boards:testboard/5

### ISSUE THREAD

**Issue by grepsuzette** [gnolang/gno#2183]
The article at https://gno.land/r/demo/boards:testboard/5 contains some `gnokey` examples that should be changed, from `--broadcast true` to `-broadcast`.

# Description

The help at https://gno.land/r/demo/boards:testboard/5 can be conveniently found by googling "gnokey addpkg".

This help is very useful and was updated (replayed?) by @moul 2 days ago.

The gnokey commands however fail showing the syntax ("USAGE  addpkg [flags] <key-name>").

For example:
```
./build/gnokey maketx addpkg test1 --pkgpath "gno.land/p/demo/avl" --pkgdir "examples/gno.land/p/demo/avl" --deposit 100000000ugnot --gas-fee 1000000ugnot --gas-wanted 2000000 --broadcast true --chainid portal-loop --remote localhost:26657
```
Gives:
```
USAGE
addpkg [flags] <key-name>
```

# Reason

Syntax error most likely happens because `--broadcast true` is not working anymore (now it works with e.g. `-broadcast=true` or simply `-broadcast`).

`true` is probably taken as a second, unwanted `<key-name>`.

# Proposed action

The code works as expected, there is no bug.
But the commands shown at https://gno.land/r/demo/boards:testboard/5 should be updated.

**Comment by thehowl** [comment]
>This help is very useful and was updated (replayed?) by @moul 2 days ago.

Yes, this is replayed, portal loop (gno.land) is regularly re-started and this post is a part of the genesis transactions.

Make a PR to update `gno.land/genesis/genesis_txs.jsonl`, updating the relevant TX. I will approve and merge swiftly.
