### ISSUE TITLE
Should we allow smart contract access file system? It is not deterministic.

### ISSUE THREAD

**Issue by piux2** [gnolang/gno#219]
gno/stdlibs/io/ioutil/ioutil.gno 

https://github.com/gnolang/gno/blob/8cbba0a349d9ac7c3d41f1ffa97790168f0884fd/stdlibs/io/ioutil/ioutil.gno#L56

https://github.com/gnolang/gno/blob/8cbba0a349d9ac7c3d41f1ffa97790168f0884fd/stdlibs/io/ioutil/ioutil.gno#L43

**Comment by moul** [comment]
No, we shouldn’t

Do you want to make a fix PR for this?

**Comment by piux2** [comment]
Cool, let me think about how to do it right.  We could design a deterministic global files structure and directory behind that FIle and Directory APIs.  

For now, we can simply remove it from the sidlibs so that people don't accidentally use it.

I will make a pull request

**Comment by piux2** [comment]
I looked at it again.  the read file and directory method have already been removed. not an issue any more
