### ISSUE TITLE
bad command in the quickstart

### ISSUE THREAD

**Issue by Doozers** [gnolang/gno#220]
Hello,
I noticed that in the [quickstart](https://gno.land/r/boards:gnolang/4) in the section "create a comment to a post", there was an omission in the first command.
In order to create a reply the command needs 4 args (boardid, threadid, postid and body) and not 3 as indicated in the post.

If you want I can create a new board quickstart and rectify the error before requesting the change in the code of the website.

Have a nice day

![image](https://user-images.githubusercontent.com/71719097/170721053-3ebb6d16-ca7f-4bfa-8a83-26316c2d3d1b.png)
![image](https://user-images.githubusercontent.com/71719097/170721127-384b0df8-2e41-4ddd-8b28-988056559e3e.png)

**Comment by moul** [comment]
@Doozers thank you for catching this

I suggest that you start by opening a PR that will fix the file on the repo, so we have GitHub’s diff tool to help the review
