### ISSUE TITLE
[GnoVM] Aliased slice types not read properly

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#2204]
## Description

Valid Go code:

```
package main

import "fmt"

type MyType struct {
	myInt    int
	myString string
}

type MyTypeArr []MyType

func main() {
	fmt.Println(makeArr(MyType{myInt: 1, myString: "1"}, MyType{myInt: 2, myString: "2"}))
}

func makeArr(ints ...MyType) MyTypeArr {
	return ints
}
```
[Go Playground](https://go.dev/play/p/ywiqyut8fd7)

While Gno gives the following panic:
```
.: test pkg: panic: interface conversion: gnolang.Type is *gnolang.SliceType, not *gnolang.DeclaredType
```

locally, and in the [Gno Playground](https://play.gno.land/p/0m_izR0ewY7), simply `(unhandled)`.

**Comment by thehowl** [comment]
Note; using the playground code (ie. ufmt) on `master` simply returns `(unhandled)`. This comes out of the `ufmt` package, which cannot handle slices.

Running locally, using `fmt`, seems to work as long as we're not using unexported struct fields (which are not supported by my good friend `gonative`):

```
$ cat a.gno
package main

import "fmt"

type MyType struct {
        MyInt    int
        MyString string
}

type MyTypeArr []MyType

func main() {
        fmt.Println(makeArr(MyType{MyInt: 1, MyString: "1"}, MyType{MyInt: 2, MyString: "2"}))
}

func makeArr(ints ...MyType) MyTypeArr {
        return ints
}
$ gno run a.gno
[{1 1} {2 2}]
```

But the panic you posted, @leohhhn, is different and seems to come from using `gno test`. Can you please provide better replication instructions?

**Comment by zivkovicmilos** [comment]
@leohhhn 

Is this issue still relevant?

**Comment by thehowl** [comment]
Closing for lack of replication instructions.
