### ISSUE TITLE
GnoSDK MVP

### ISSUE THREAD

**Issue by moul** [gnolang/gno#2205]
This issue defines the V1 or MVP version of the future GnoSDK (#873). This version is essential for test4 and the launch, while the broader GnoSDK issue focuses on making GnoSDK reusable for new TM2+GnoVM chains, which isn't a current priority.

## Goals

- **Simplicity and Reliability**: Prioritize simplicity and reliability, even if performance is not highly optimized.
- **Clean API/Usage**: Ensure the API and usage are clean, especially for smart contracts. Avoid using the recently introduced `std.Emit` event system for data exchanges, as emitted events are not as explicit and simple to test as returned typed values.

## Suggested Implementation

- Develop helpers to call a contract's functions from the gnoland app.
- Implement proper error management and data marshalling.
- Include options such as "read-only" (execute without saving realm changes).

## Expected Usages

- `r/sys/names` #1107 
- `r/sys/valset` #1945
- `r/sys/vals` #2130 
- `r/sys/teams` #2184 
- `r/sys/eula`
- `r/sys/vars`

**Comment by zivkovicmilos** [comment]
Completed :)
