### ISSUE TITLE
[GnoVM/TM2] Limiting package functionality 

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#2224]
## Description

As discussed on the Belgrade retreat, we came to conclusions about pure packages:
- We should forbid direct calls to `p/` via `maketx call`, `qeval`, or other. In essence, `p/` should be only callable by other code (while on this note, we should also forbid the same for stdlibs - [reference comment](https://github.com/gnolang/gno/issues/1538#issuecomment-1911939360))
- We should panic if `p/` tries to get any type of banker (or possibly allow only ReadOnly banker?)
- We should panic if the user tries to change state in a `p/`, instead of just letting the transaction go through without applying the state change - [related issue](https://github.com/gnolang/gno/issues/1538)

 
cc @moul

**Comment by moul** [comment]
Can you merge with #2192 ?

**Comment by leohhhn** [comment]
Closing in favor of #2192
