### ISSUE TITLE
[gnokey] Add support for queries on a specific height

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#2231]
## Description

Currently, calling queries at a specific height is not supported, even though the `--height` flag exists in `gnokey`. We should either implement this, or remove the flag until the functionality is implemented. Same goes for the `--prove` flag.

**Comment by moul** [comment]
What are you hoping to query at a specific height? Do you have any hypothetical `gnokey` usage examples to share?

**Comment by linhpn99** [comment]
https://github.com/gnolang/gno/pull/2234
@leohhhn Consider this PR  if we don't have a specific plan for implementing the logic for the two mentioned commands

**Comment by moul** [comment]
I’m against supporting custom height for balance checking. This is the role of an indexer, like Gnoscan. I suggest making feature requests to them or the DevX team, or consider defining specs for a new indexer.

I stay open for other queries such as retrieving a full block or something that’s cheap to compute.
