### ISSUE TITLE
faucet.gnoteam reCaptcha for dSocial faucet does not load

### ISSUE THREAD

**Issue by grepsuzette** [gnolang/gno#2257]
### How to reproduce

Go to https://faucet.gnoteam.com/
Click on the dSocial faucet button

The reCaptcha then appears with this error: 

![Screenshot 2024-06-02 at 07-46-15 Gno Faucet Hub](https://github.com/gnolang/gno/assets/350354/55bb5e33-86f5-4d15-8292-09ee91d305ad)

Text is `ERROR for site owner: Invalid domain for site key`

### System used

Firefox 126.0 Debian package behind proxy

### Console

Not sure anything useful TBH.
Those 2 warnings however appear each time the dSocial faucet button is clicked:

![Screenshot from 2024-06-02 08 16 47](https://github.com/gnolang/gno/assets/350354/28690555-188d-4407-8aba-1d30c1caf8a7)

**Comment by zivkovicmilos** [comment]
Hey @grepsuzette,

We moved the official faucet hub to https://faucet.gno.land

The reCaptcha is tied to a domain, and it doesn't work if the domain is not defined in the settings (gnoteam isn't)
