### ISSUE TITLE
Missing return value error in Poll tutorial

### ISSUE THREAD

**Issue by Molaryy** [gnolang/gno#2310]
## Description

I was testing the [how to write a simple dApp](https://docs.gno.land/how-to-guides/write-simple-dapp) with @agherasie  and we found out that the code given for the package doesn't work when trying to deploy it with gnokey.

This is the error that we got:
![Screenshot 2024-06-08 at 18 04 14](https://github.com/gnolang/gno/assets/95973236/411b4b68-8e2a-4b66-93d5-684243c6934a)

It happens at line 67 in the function VoteCount:
```go
func (p Poll) VoteCount() (int, int) {
    var yay int

    p.Voters().Iterate("", "", func(key string, value interface{}) bool {
        vote := value.(bool)
        if vote == true {
            yay = yay + 1
        }
    })
    return yay, p.Voters().Size() - yay
}
```

we solved this problem by adding a return false at the end of Iterate:
```go
p.Voters().Iterate("", "", func(key string, value interface{}) bool {
        vote := value.(bool)
        if vote == true {
            yay = yay + 1
        }
        return false
    })
```

Like the [tree package](https://gno.land/p/demo/avl/tree.gno) says when the callback returns true, the iteration is stopped, so by adding false we will reach every vote.

**Comment by leohhhn** [comment]
Thanks for noticing this - if you want, you can make a PR to fix it in the docs :)

**Comment by agherasie** [comment]
> Thanks for noticing this - if you want, you can make a PR to fix it in the docs :)

Opened https://github.com/gnolang/gno/pull/2356 to solve this !
