### ISSUE TITLE
`Time.Now()` always return initial UNIX time

### ISSUE THREAD

**Issue by notJoon** [gnolang/gno#2348]
## Description

Found this while checking #2076 

When you call `time.Now()`, it should return the elapsed time since `UTC January 1, 1970 00:00:00`. However, when you call this function and print the time as shown below, it outputs the value `1970-01-01 00:00:00 +0000 UTC m=+0.000000001`. It seems that instead of the elapsed time from that point, it is printing that point in time itself.

```go
package main

import (
	"time"
)

func main() {
	umt := time.Now()
	println(umt)
}

// output:
1970-01-01 00:00:00 +0000 UTC m=+0.000000001
````

When you run the code below, it prints the current time in the format `YYYY-MM-DD HH-MM-SS`, and you can see the initial UNIX time is displayed.

```go
import (
	"time"
)

func main() {
	umt := time.Now().UTC().Format("2006-01-02 15:04:05")
	println(umt)
}

// output:
1970-01-01 00:00:00
```

Currently, there are two version of `time.Now()`: one that is a ported version of the Go standard library and another that is handled by native binding. I'm not sure which one is actually being called, but I think the latter implmentation will be executed.

The function implemented with native binding calculates the time using the `Timestamp` and `TimestampNano` fields of `ExecContext`. I suspect that these fields might be storing a value of `0`, causing all times to be output as the UNIX epoch time.

https://github.com/gnolang/gno/blob/a1ab6a190cbd6082160244a42dd2b257c2254a68/gnovm/stdlibs/std/context.go#L10-L22

https://github.com/gnolang/gno/blob/a1ab6a190cbd6082160244a42dd2b257c2254a68/gnovm/stdlibs/time/time.go#L10-L17

**Comment by grepsuzette** [comment]
In case of a main() run with `gno run your_main.gno` it's the second case you mention. So:
https://github.com/gnolang/gno/blob/a1ab6a190cbd6082160244a42dd2b257c2254a68/gnovm/stdlibs/native.go#L945-L957

calls...
https://github.com/gnolang/gno/blob/a1ab6a190cbd6082160244a42dd2b257c2254a68/gnovm/stdlibs/time/time.go#L10-L17

where the machine is set, but `m.Context == nil` (I tested this adding panics and recompiling the code)

**Comment by jefft0** [comment]
Hello @notJoon . Do you think this could be related to the `Time.Now()` issue reported in https://github.com/gnolang/gno/issues/2960 ?

**Comment by notJoon** [comment]
> Hello @notJoon . Do you think this could be related to the `Time.Now()` issue reported in #2960 ?

not sure, but maybe related 🤔🤔🤔🤔🤔

**Comment by thehowl** [comment]
https://github.com/gnolang/gno/issues/851#issuecomment-2429753760

@MikaelVallenet is going to take up a larger refactor of `time` - I think we can also move `time.Now()` in testing to be at the time of doing the tests. Though I think this should be purely aesthetical; it should not shift in the test as we shouldn't be giving the system time, even during tests (because the time won't ever be changing when you work on-chain).

**Comment by thehowl** [comment]
I'll close this in favour of #851, as I think this issue adds little additional context to that anyway.
