### ISSUE TITLE
uassert/urequire: Wrong message when strings are not the same.

### ISSUE THREAD

**Issue by ajnavarro** [gnolang/gno#2502]
### Description

When using uassert.Equal or urequire.Equal with strings and they are not the same, the provided error message is wrong. 

### Your environment

* OS and version: Linux 
* version of gno: [v0.1.0-nightly.20240627](https://github.com/gnolang/gno/releases/tag/v0.1.0-nightly.20240627)
* branch that causes this issue (with the commit hash): [master](https://github.com/gnolang/gno/commit/da59516221093e1c5856132df03946b89e17d026)

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behavior

```
uassert.Equal: same type but different value
        expected: No proposals found :(.
        actual:  OBTAINED STRING
```

### Actual behavior

```
uassert.Equal: same type but different value
        expected: No proposals found :(.
        actual:   unsupported type
```

**Comment by linhpn99** [comment]
Here is the hotfix PR https://github.com/gnolang/gno/pull/2507
