### ISSUE TITLE
CI should detect problems in PRs, not after merging

### ISSUE THREAD

**Issue by moul** [gnolang/gno#2531]
We had at least 3 merged pull requests in the last few days (two of them were mine, sorry), and they were green while still unmerged, but they caused the master branch to become red.

We need to fine-tune the CI to prevent this from happening.

**Comment by thehowl** [comment]
The case I saw today was caused by a PR in examples/, changing the behaviour of a test in gno.land/ (a txtar test).

I'm starting to think we should just test everything all the time, also on PRs.

**Comment by thehowl** [comment]
Done with https://github.com/gnolang/gno/pull/2625
