### ISSUE TITLE
No linters are enabled

### ISSUE THREAD

**Issue by alikhil** [gnolang/gno#255]
Hi!

I would suggest to enable some linters on this repo. For example by using [golangci-lint](https://golangci-lint.run/).

It will help to catch some bugs early and keep code quality at good level.

This is a short list of potential bugs found by `staticcheck` linter:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/7482065/174675211-01579375-c02e-4c39-8f33-a50619ae17f5.png">

**Comment by alikhil** [comment]
@moul @jaekwon what do you think about it?
If you think that it would be useful then I can spend some time to configure it

**Comment by moul** [comment]
Yep, I like the idea, and I can monitor over time to adjust the config if needed

**Comment by thehowl** [comment]
Done with #472
