### ISSUE TITLE
Discord roles

### ISSUE THREAD

**Issue by kazai777** [gnolang/gno#2591]
## Description
It would be nice to define roles for the `gnoland` discord. Lately there are often scams coming from accounts called `ANNOUNCEMENTS`. I'm aware that the current discord server admins don't necessarily have the time to check these kinds of messages all the time, which is why it would be a good idea to set up some trusted users who could delete these kinds of messages quickly when they're there. The server currently has `6.37k` users, so I think it would be important to be able to quickly moderate this type of messages, so that members don't get scammed.

**Comment by Kouteki** [comment]
@michelleellen I see a couple of items to unpack here:

- Only a few team members are tagged as "crew". The community members don't know if they are engaging a team member, an impersonator, or another community member
- We can get a couple of active community members to help with discord moderation
- Our turnaround for moderation is horrible. Malicious links stay up for hours, sometimes even days

**Comment by kazai777** [comment]
> @michelleellen I see a couple of items to unpack here:
> 
> * Only a few team members are tagged as "crew". The community members don't know if they are engaging a team member, an impersonator, or another community member
> * We can get a couple of active community members to help with discord moderation
> * Our turnaround for moderation is horrible. Malicious links stay up for hours, sometimes even days

I don't know if it's possible, but it would also be nice to ban usernames containing `announcements`.

**Comment by michelleellen** [comment]
@kazai777 thanks for the feedback, and help moderating the Discord. We are working on revamping the Discord completely with new roles, and channels. We can probably discuss next week during office hours our proposals.

**Comment by michelleellen** [comment]
Hey @kazai777 thanks to @Ticojohnny we've made some major improvements to Discord. Let us know your feedback.
