### ISSUE TITLE
[infra] Minimal Setup of Observability node running monitoring service

### ISSUE THREAD

**Issue by sw360cab** [gnolang/gno#2632]
The node should be able to run services for:
- receiving logs
- handling metrics or OpenTelemetry
- setup and send alerts

The target could be:
- an in-place node
- an existing node (Test4-RPC1 or Portal Loop)

Explore different technologies:
- Loki
- Grafana Alloy
- Elastic Observability

**Comment by sw360cab** [comment]
Closed in favor of #2618

**Comment by thehowl** [comment]
Linear re-opened this, but it's incorrect.
