### ISSUE TITLE
Panic on Type Assertion with Interface

### ISSUE THREAD

**Issue by omarsy** [gnolang/gno#2636]
## Description:
**Issue Summary:**

A panic occurs when performing a type assertion on an `interface{}` in Gnolang. The following code works as expected in Go (Golang), but in Gnolang, it results in a runtime panic:

```go
package main

import "fmt"

func main() {
	var i interface{} = 1
	var a, ok = i.(int)
	fmt.Println(a, ok)
}
```

**Expected Behavior:**

The code should execute without panic, correctly performing the type assertion. The expected output should be:

```
1 true
```

**Actual Behavior:**

In Gnolang, running the above code causes a panic with the message:

```
panic: interface conversion: gnolang.Expr is *gnolang.TypeAssertExpr, not *gnolang.CallExpr
```

This suggests an issue with how type assertions are being handled internally, specifically when converting types within the interface.

**Comment by thehowl** [comment]
yes; we should unify the code for DeclStmt and AssignStmt (ie. `:=` and `var x =`); as they are supposed to be almost equivalent in the go spec but they do very different things in preprocess

**Comment by omarsy** [comment]
Yes, I think too. I don't know why we didn't do that.
