### ISSUE TITLE
[infra] GnoFaucet - Create Healthcheck enpoint

### ISSUE THREAD

**Issue by sw360cab** [gnolang/gno#2650]
Create an HTTP endpoint responding to GET requests to be used as HEALTCHECK endpoint for Gno Faucet service.

The endpoint is supposed to answer 200 on healthy service, no specific body or content-type is required.

**Comment by zivkovicmilos** [comment]
Addressed in https://github.com/gnolang/faucet/pull/49

We should open a cross PR on the gno repo when we do a release for `gnolang/faucet`
