### ISSUE TITLE
Gno Playground - deploy on portal loop does not take my namespace input

### ISSUE THREAD

**Issue by MikaelVallenet** [gnolang/gno#2682]
### Description

I'm trying to deploy a simple hello world realm on the portal loop where I've registered my namespace (cf. https://gno.land/r/demo/users). but it does not read my input and try to deploy to /r//<realm_name>.

I tried to set my input equal to my address too, but I didn't have this problem when I deploy on testnet 4 and the deployment modal pre-fills my address.

I can deploy under my namespace using the CLI but cannot using gno playground.
I think it's just reading the namespace entry that doesn't work.

https://www.loom.com/share/75b0c3cd27324edaaac642f49fbe908c?sid=da4451fb-4044-4678-8173-ef3f4ea6ea57

### Your environment

* Google Chrome: Version 127.0.6533.88 (Official Build) (64-bit)
* Adena: Version 1.11.0

### Steps to reproduce

* Register username as namespace on portal loop
* Use the web UI to deploy under your namespace

### Expected behaviour

deploy the contract and render here: https://gno.land/r/mikaelvallenet/hello

### Actual behaviour

Error:

```
msg:0,success:false,log:--= Error =--
Data: vm.InvalidPkgPathError{abciError:vm.abciError{}}
Msg Traces:
    0  /home/runner/work/gno/gno/gno.land/pkg/sdk/vm/errors.go:44 - invalid package/realm path "gno.land/r//hello", failed to match "^gno\\.land\\/(?:p|r)(?:\\/_?[a-z]+[a-z0-9_]*)+$"
Stack Trace:
    0  /home/runner/work/gno/gno/tm2/pkg/errors/errors.go:20
    1  /home/runner/work/gno/gno/gno.land/pkg/sdk/vm/errors.go:44
    2  /home/runner/work/gno/gno/gno.land/pkg/sdk/vm/keeper.go:381
    3  /home/runner/work/gno/gno/gno.land/pkg/sdk/vm/handler.go:44
    4  /home/runner/work/gno/gno/gno.land/pkg/sdk/vm/handler.go:31
    5  /home/runner/work/gno/gno/tm2/pkg/sdk/baseapp.go:646
    6  /home/runner/work/gno/gno/tm2/pkg/sdk/baseapp.go:823
    7  /home/runner/work/gno/gno/tm2/pkg/sdk/baseapp.go:577
    8  /home/runner/work/gno/gno/tm2/pkg/bft/abci/client/local_client.go:82
    9  /home/runner/work/gno/gno/tm2/pkg/bft/appconn/app_conn.go:74
   10  /home/runner/work/gno/gno/tm2/pkg/bft/state/execution.go:265
   11  /home/runner/work/gno/gno/tm2/pkg/bft/state/execution.go:102
   12  /home/runner/work/gno/gno/tm2/pkg/bft/consensus/state.go:1370
   13  /home/runner/work/gno/gno/tm2/pkg/bft/consensus/state.go:1294
   14  /home/runner/work/gno/gno/tm2/pkg/bft/consensus/state.go:1240
   15  /home/runner/work/gno/gno/tm2/pkg/bft/consensus/state.go:1271
   16  /home/runner/work/gno/gno/tm2/pkg/bft/consensus/state.go:1684
   17  /home/runner/work/gno/gno/tm2/pkg/bft/consensus/state.go:1518
   18  /home/runner/work/gno/gno/tm2/pkg/bft/consensus/state.go:696
   19  /home/runner/work/gno/gno/tm2/pkg/bft/consensus/state.go:655
   20  /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/asm_amd64.s:1695
--= /Error =--
,events:[]
```

**Comment by leohhhn** [comment]
Hey @MikaelVallenet, thanks for opening up this issue. This is a known bug and is being fixed right now by the team.

**Comment by leohhhn** [comment]
This was fixed.

**Comment by thehowl** [comment]
Linear re-opened this, but it's incorrect.
