### ISSUE TITLE
Datatype's underline array is persisted as *uint8 pointer value 

### ISSUE THREAD

**Issue by piux2** [gnolang/gno#2704]
## Description

Problem: 

A ByteTypeValue should not be persisted as it contains the underline array.  However when it is assigned to a uint8 PointerType variable , the underlien array got persisted

Testing Case:

// PKGPATH: gno.land/r/test
package test

var a0, a1 *uint8

func main() {
	a := []byte("helloooooooooooooooooooooo")
	a1 = &a[1]
	a0 = &a[0]

}

// Realm:
// switchrealm["gno.land/r/test"]
+c[a8ada09dee16d791fd406d629fe29bb0ed084a30:4]={
+    "Data": "aGVsbG9vb29vb29vb29vb29vb29vb29vb28AAAAAAAA=", <<<< "helloooooooooooooooooooooo"
+    "List": null,
+    "ObjectInfo": {
+        "ID": "a8ada09dee16d791fd406d629fe29bb0ed084a30:4",
+        "IsEscaped": true,
+        "ModTime": "0",
+        "RefCount": "2"
+    }
+}

**Comment by piux2** [comment]
This is not a bug. We can change the value of a0, which can modify the underlying array. Therefore, the underlying array needs to be persisted.

**Comment by thehowl** [comment]
Linear re-opened this, but it's incorrect.
