### ISSUE TITLE
Unexpected Boolean Comparison Results

### ISSUE THREAD

**Issue by notJoon** [gnolang/gno#2719]
## Description

A weird behaviour has been discovered in the boolean comparison logic, especially when using the comparison operator.

```go
package main

func main() {
    a := "1234"
    b := "1234"

    cond := a == b
    println(cond)
    println(cond == (a == b))
    println(cond && (a == b))
    println(cond || (a > b))
}

// Output:
// true
// false
// true
// true
```
https://go.dev/play/p/7e2h2EATQjI 

In go, these are must print out `true`.

This bug was found during this [PR](https://github.com/gnoswap-labs/gnoswap/pull/326)

**Comment by notJoon** [comment]
closed. It was a version issue.

**Comment by notJoon** [comment]
I thought it was version problem, but it wasn't. so reopen the issue

**Comment by thinhnx-var** [comment]
Look like something was wrong with version or environment? IDK exactly but when I tested with gno playground `GnoVM - V0.0.1-Dev-24-06-01`, result was like expectation
![image](https://github.com/user-attachments/assets/63684817-35e6-4926-aee7-733c1f670291)

**Comment by notJoon** [comment]
@thinhnx-var As far as I know, gno playground does not follow the most recent master branch version (ref: #2306). Therefore, since it cannot be reproduced in the playground, it needs to be run locally.

Below are the results of running it locally.

<img width="968" alt="스크린샷 2024-08-22 오후 12 11 06" src="https://github.com/user-attachments/assets/1015276f-e33a-49af-b65a-352388272aad">
<img width="365" alt="스크린샷 2024-08-22 오후 12 11 44" src="https://github.com/user-attachments/assets/d619b9d3-9bd7-4b2b-9252-53953c655bcb">

**Comment by thinhnx-var** [comment]
@notJoon 
Yea I see, when I use the latest `gno` binary to run that comparasion, it was wrong. This is not happen with my old version of `gno` which is not so much commits behind the master.  So lets check what we changed recently to find out the root cause.

**Comment by r3v4s** [comment]
IIRC, it used to work before this pr https://github.com/gnolang/gno/pull/1890

**Comment by ltzmaxwell** [comment]
on this.

**Comment by ltzmaxwell** [comment]
#1890  introduced strict type comparison, which is the correct approach but overlooked the problem mentioned above, resulting in the comparison between bool and untyped bool. I will provide a fix soon.

**Comment by ltzmaxwell** [comment]
it's fixed here: https://github.com/gnolang/gno/pull/2725, please review @notJoon , @r3v4s @thinhnx-var .
cc: @thehowl @deelawn for more challenges.
