### ISSUE TITLE
Immunefi Bug Bounty program

### ISSUE THREAD

**Issue by aleximmunefi** [gnolang/gno#2764]
Spoken with Leon on your Discord
I wanted to see if Gno Land will benefit from an Immunefi Bug Bounty program

If so, please dm me on Telegram - @aleximmunefi

[Immunefi Deck v4 - Consolidated.pdf](https://github.com/user-attachments/files/16906269/Immunefi.Deck.v4.-.Consolidated.pdf)

**Comment by kristovatlas** [comment]
Hey @aleximmunefi, we actually spoke with Immunefi earlier this about a general bounty program for All in Bits. The proposal was out of our price range, but we'll circle back to considering Immunefi down the road. Thanks!

**Comment by thehowl** [comment]
Linear re-opened this, but it's incorrect.
