### ISSUE TITLE
"home of fame", an hall of fame for homepages.

### ISSUE THREAD

**Issue by moul** [gnolang/gno#2772]
Here is the improved text:

Let's create a Hall of Fame to recognize participants in the "Home" competition.

The registration process should be handled by the contract itself, using a simple function like `halloffame.Register("my description")`.
This function will extract the username and path of the calling contract (`std.PrevRealm()`), and create an entry with the provided description.

See https://github.com/gnolang/gno/pull/2551/files#diff-ac18c4e6b22afbbd3707fcf3312a75a95afe616b6f07gccbf14d5521759abb59R14-R23. 
If needed, I can extract additional details like `p/fqname` from the unmerged PR.

Additionally, we can add moderation functions such as `AdminRemoveEntry` and `AdminPauseSubmissions`.

**Comment by moul** [comment]
Use GitHub.

**Comment by michelleellen** [comment]
@moul for the home competition and registering for hall of fame, is there a competition criteria to qualify for home of fame, or it is a directory initially of all home realms that can eventually be ranked?
