### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by blockcreators** [gnolang/gno#28]
So currently as far as I can see, the documentation is mainly in the readme file and scattered elsewhere.
People initially are hit with the readme, but might want to see the other areas of the project. 
So it might be better to split the documentation into specific modules.

How about set up docs.gnolang.com as the documentation site and also put the bulk of the current documentation there.
You could use gitbook (I've used it before and it seems good, and free to use for opensource projects like this)

Let me know if I can help!

**Comment by darksoulcrypto** [comment]
VuePress?

**Comment by moul** [comment]
With things like https://gno.land/r/boards?help, we could keep the focus on making the system generating automatic documentation as much as possible.

There are various enhancements we can do:
* [ ] support function-level comments
* [ ] support package-level comments
* [ ] generate various machine-readable formats (swagger?)
* [ ] support comments-based "examples" -> could be done in the package-level comments

And other topics which are not related to the code, such as user doc etc:
* [ ] continue improving and using `r/boards:gnolang`?
* [ ] ask help from the community to maintain some good references, etc?

**Comment by moul** [comment]
closing since very old and documentation was updated a lot since and has ongoing improvements too.
