### ISSUE TITLE
setup `gnobro` hosting

### ISSUE THREAD

**Issue by gfanton** [gnolang/gno#2807]
For now, `gnobro` is self-hosted, but we want to move it to a more legitimate server.

### Requirements
-  `gnobro` is lightweight; it currently runs on a simple x86 machine with 3 vCPUs and 4 GB of RAM.
-  It needs to be accessible on the default SSH port (22) to be fully usable as `ssh xxx.yyy`.
-  @sw360cab mentioned that we will likely need a Docker image.

**Comment by Olawale-22** [comment]
nice work

**Comment by Kouteki** [comment]
@sw360cab what is the status of this issue?

**Comment by sw360cab** [comment]
LGTM, @gfanton are we ok to close or there are other config steps missing?
