### ISSUE TITLE
NO informations about *_filetest.gno in the docs

### ISSUE THREAD

**Issue by MalekLahbib** [gnolang/gno#2818]
## Description
I always noticed some z_*_filetest.gno format in some examples or folders but never understood what it is and how it works. But after a discussion yesterday with @moul, who made me a quick demo on how it works and explained to me that it's a gno ecosystem specific thing and that there's no documentation about how it works and how to use it ( "gno test -v -update-golden-tests=true ." command for example), I wanted to ask: have you planned to write a documentation about it with examples?
@leohhhn @michelleellen

**Comment by thehowl** [comment]
Please no.

https://github.com/gnolang/gno/issues/1346

Use normal tests; and implement features in the normal testing framework if they don't do what you need (compared to filetests). filetests should really only be used as an internal mechanism for those developing on the GnoVM, as it doesn't depend on the `"testing"` package to exist, and thus can be used to test for "low-level" things.
