### ISSUE TITLE
GnoVM: Constant expressions do not work with some built-in functions

### ISSUE THREAD

**Issue by omarsy** [gnolang/gno#2829]
#### Description
In Go, the following code snippet compiles and runs correctly, using the built-in `min`/ `max` function within a constant expression:

```go
package main

func main() {
	const t = min(0, 1)
	println(t)
}
```

However, when using the same code in Gno, it returns an error:

```
name min not defined in fileset with files 
```

#### Expected Behavior
The code should compile successfully in Gno, similar to how it works in Go, allowing the use of built-in functions in constant expressions.

**Comment by leohhhn** [comment]
As far as I can see, `min` & `max` were [introduced in Go 1.21](https://tip.golang.org/doc/go1.21#language); Gno is based on 1.17, so this is not supported yet.

**Comment by thehowl** [comment]
if you find this is the case for other constant expressions (like `len([2]int{1, 2})`, which should yield the constant-expr `2`), then please open another issue.

as leon said, min/max are not supported yet, we'll need generics #1748 before that

**Comment by omarsy** [comment]
maybe we should return the right error for "name min/max not declared"

**Comment by thehowl** [comment]
yeah, you're welcome to adapt the error message, i agree it's unclear.
