### ISSUE TITLE
`gno run` should have an ExecContext

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#2834]
similar to testing exec context, to support functions like `std.GetHeight()`. It currently doesn't:

https://github.com/gnolang/gno/blob/9897b667450ad59b6ad21b23b994e9f13d97ca4f/gnovm/cmd/gno/run.go#L115-L121

cc @wyhaines

**Comment by wyhaines** [comment]
So....I have a branch that implements this. It is based on how it works for the 'test' command. I'll clean it up a bit and provide a PR.
