### ISSUE TITLE
GnoVM: Expose methods of exported struct variables to the `MsgCall` API

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#2835]
## Description

If a realm has an exported variable of a custom struct type, which has exported methods with primitive arguments on it, these methods should be exposed to the `MsgCall` API in the following way:

```go
package rlm 
// pkgpath is gno.land/r/leon/rlm

type Foo struct {
	num int
}

var MyFoo = &Foo{ num: 0 }

func (f *Foo) UpdateNum(newNum int) { // should be exposed
	f.num = newNum
}

func (f *Foo) unexportedMethod() { // should not be exposed
	...
}

func (f *Foo) ExportedComplexArgMethod(slice []*int) { // should not be exposed
	...
}
```

Users should be able to call the `UpdateNum` method like so:

```bash
gnokey maketx call -good-flag-name "gno.land/r/leon/rlm.MyFoo.UpdateNum" -arg "2" 
```
while not being able to call `MyFoo.unexportedMethod()` & `MyFoo.ExportedComplexArgMethod()`.

The other issue is how to manage flags in `gnokey`; currently, the `pkgpath` and `func` flags are separate. Another semantic issue is that there is a distinction between functions and methods. Possibly, this can be solved with an `-endpoint` flag, which could have this usage:

```bash
gnokey maketx call -endpoint "gno.land/r/leon/rlm.MyFoo.UpdateNum" -arg "2"
```

I am not sure that this is the right way to use it in `gnokey`, so I am open to other suggestions.

**Comment by moul** [comment]
Duplicate of https://github.com/gnolang/gno/issues/1045

**Comment by leohhhn** [comment]
Closing as this is a duplicate.
