### ISSUE TITLE
Uint64 overflow

### ISSUE THREAD

**Issue by MalekLahbib** [gnolang/gno#2839]
## Description
I was going through the GRC20 package, and noticed in banker.gno file some comments form @moul ``` // TODO: check for overflow```. So I made a test and called a function with overflow and had this:
![Screenshot from 2024-09-24 11-23-23](https://github.com/user-attachments/assets/5b6ff545-bf54-4ab3-a18d-444484ad9f61)

From what I understand, it's not possible for the moment to check for the overflow in the file, as the panic message seems to come from the VM.

Am I right? Is this the way things are supposed to work?

I imagine that it's not necessary to check for overflow in the code if the VM will do it automatically and not let the function execute.

**Comment by leohhhn** [comment]
Can you please provide the code you used?

Seems that the error you're getting is from `strconv.ParseUint`, not a VM panic.

**Comment by MalekLahbib** [comment]
I tried to put a condition in the beginning of the function to verify the overflow:
![Screenshot from 2024-09-24 13-56-38](https://github.com/user-attachments/assets/ad2bacc1-aee6-4940-acb1-5f223ec7419c)

but I don't think the error message is from the function execution, I said VM as I still don't understand so much how it's working. It says in the beginning:
--= Error =--
Data: internal error
Msg Traces:
    0  /home/malek/gno/tm2/pkg/crypto/keys/client/maketx.go:215 - deliver transaction failed: log:recovered: error parsing uint64 "18446744073709551616": strconv.ParseUint: parsing "18446744073709551616": value out of range

Am I wrong?

**Comment by leohhhn** [comment]
Hey, check the errors again. This error is coming from `gnokey`, which means that it has not even reached the VM or your Gno code yet.

**Comment by MalekLahbib** [comment]
![image](https://github.com/user-attachments/assets/f66861c2-2c87-4edd-bf64-11f0b3842876)

So ```// TODO: check for overflow``` that @moul wrote here in the banker.gno file can't be done as it seems that gnokey is  checking for overflow before the code is executed.

**Comment by MikaelVallenet** [comment]
> ![image](https://private-user-images.githubusercontent.com/111009238/370716836-f66861c2-2c87-4edd-bf64-11f0b3842876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTIzOTUsIm5iZiI6MTcyNzM1MjA5NSwicGF0aCI6Ii8xMTEwMDkyMzgvMzcwNzE2ODM2LWY2Njg2MWMyLTJjODctNGVkZC1iZjY0LTExZjBiMzg0Mjg3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxMjAxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOThmN2M5ZTUzNTdkNTM0MTkwNzkyYTFjYzk4OTg1ZDRjMDM1ODRkNjdmMzI1MDhmN2MwOGFhM2M5MTY1ZmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E57fXVd1VBIjElcakRY0sUtgambZWcp7l6VIgSy8qTU)
> 
> So `// TODO: check for overflow` that @moul wrote here in the banker.gno file can't be done as it seems that gnokey is checking for overflow before the code is executed.

I think the overflow to control is the ``b.totalSupply += amount`` 

e.g:
total_supply = UINT64_MAX - 1
amount = 2

avoid that total_supply - amount overflow, by panic i guess

**Comment by thehowl** [comment]
Hey, please read the stacktrace. This comes from convertArgToGno in the VM keeper.

The argument cannot be parsed by `strconv.ParseUint` when attempting to transform it into an argument for the VM. In general, to check the behaviour on overflow you'll have to get to `(1 << 64) - 1`, then add values on top of it.

I don't exactly know what you were attempting, but a better strategy can be to try using MsgRun. Anyhow, here if anything what we should do is an improvement on the error message. For housekeeping, I'll be closing the issue (the error is expected)

**Comment by MalekLahbib** [comment]
> I don't exactly know what you were attempting, but a better strategy can be to try using MsgRun. Anyhow, here if anything what we should do is an improvement on the error message. For housekeeping, I'll be closing the issue (the error is expected)

my issue was related to [this](https://github.com/gnolang/gno/issues/2839#issuecomment-2373994700). I was trying to add the check for overflow that @moul asked about, but with the comment of @MikaelVallenet it's more clear to me.
