### ISSUE TITLE
Discord discussion with @leohhhn

### ISSUE THREAD

**Issue by aleximmunefi** [gnolang/gno#2899]
I would like to speak to the project team about how you currently manage bug reports and code upgrades to maintain safety on your project

Please dm me on Telegram @aleximmunefi or email me on alexander.kaitiff@immunefi.com

**Comment by thehowl** [comment]
We already [discussed](https://github.com/gnolang/gno/issues/2764) a few weeks ago, and our GitHub is not a venue for marketing your product.

We'll be in touch if we're re-considering again. Please don't open further issues or ask to establish further unsolicited lines of contact on this space, or I'll make sure to see you out. Thanks.
