### ISSUE TITLE
[bug] bad import in manfred_outfmt realm

### ISSUE THREAD

**Issue by MalekLahbib** [gnolang/gno#2903]
## Description
![Screenshot 2024-10-04 at 15 16 14](https://github.com/user-attachments/assets/0472cef0-3b3e-44ca-a755-cd87813e547d)

I think this file needs to be updated @moul @leohhhn @thehowl.

![Screenshot 2024-10-04 at 15 20 37](https://github.com/user-attachments/assets/12ea7f82-3c6f-4721-a397-d1ada3e769dd)

**Comment by leohhhn** [comment]
The tooltip you got might not be 100% accurate and might not fully trustable; can you see if a test is failing or something more concrete? If it is, you're welcome to open a PR to fix it.

**Comment by thehowl** [comment]
yes, outfmt is not really working. It has a `// Draft` comment which excludes it from being published on gno.land.

**Comment by moul** [comment]
It can be removed if "Draft" isn't enough; I will revisit this notion of conditional rendering format (but not json) later, because I think it can become useful common.

**Comment by MalekLahbib** [comment]
The thing is I had this erro msgs since I installed @gfanton gnopls. It's red for "outfmt", 'package not declared" test and "several-lint-errors".

![Screenshot 2024-10-07 at 11 40 02](https://github.com/user-attachments/assets/ca649c0a-10e4-4280-bb70-1e4bc5a3525b)

**Comment by gfanton** [comment]
As mentioned by @moul and @thehowl, it's a `// Draft` package and should be ignored by `gnopls`. 
@MalekLahbib Can you open an issue on the `gnopls` repository instead? 
closing this for now.
