### ISSUE TITLE
Migrate community-first repos to gnoverse

### ISSUE THREAD

**Issue by Kouteki** [gnolang/gno#2909]
## Current state

The gnolang org contains more than it should, such as:
- Projects that aren't related to the infrastructure
- Projects that are built and maintained by the community

As a result, this causes unnecessary delays, complexity and centralization of authority.

## Desired state

Gnolang contains only infrastructure specific projects, and projects owned by the gno.land core team. The remaining projects live in the [gnoverse](https://github.com/gnoverse) organization, where the contributors have a larger role to play and greater authority.

## Projects to be migrated

- [x]  tlin
- [x] intellij-gno
- [x] dsocial
- [x] vscode-gno
- [x] awesome-gno
- [x] memeland
- [x] gh-sql
- [x] govdao-web
- [x] *gc24*
- [x] gnochess
- [x] community-faucet-bot
- [x] gnoffee
- [x] gh-labels
- [x] acs

## Bonus cleanup
- [x] goleveldb: DELETE
- [x] gno-repository-template: archive/delete
- [x] bounties: ARCHIVE (keep main)

**Comment by moul** [comment]
i've:
- added a @gnoverse README
- moved awesome-gno + pinned
- updated @gnolang's README to link to @gnoverse

**Comment by moul** [comment]
Depending on how the discussion goes, this tool might also be relevant: https://github.com/gnolang/gnostats-ui/issues/1

**Comment by Kouteki** [comment]
Each repo will have a dedicated team as maintainers, and access control will be through teams (i.e. no individuals added as maintainers). 

Teams to be created and current maintainers invited:

- [ ]  tlin
- [ ]  intellij-gno
- [ ]  dsocial
- [ ]  vscode-gno
- [ ]  memeland
- [ ]  gh-sql
- [ ]  govdao-web
- [ ]  gc24
- [ ]  gnochess
- [ ]  community-faucet-bot
- [ ]  gnoffee
- [ ]  gh-labels
- [ ]  acs
