### ISSUE TITLE
bug: `gnokey list` on help page links to a bad url

### ISSUE THREAD

**Issue by MalekLahbib** [gnolang/gno#2925]
## Description
when doing a test, I clicked on ```see `gnokey list` ``` on help page on ```https://test4.gno.land/r/demo/users?help```

<img width="937" alt="Screenshot 2024-10-08 at 11 42 54" src="https://github.com/user-attachments/assets/7addc767-75ca-4bb3-a133-a065b29e4e0e">

and the link sent me to [this url](https://docs.gno.land/gno-tooling/cli/gno-tooling-gnokey/#list-all-known-keys) that seems to be no more good.

<img width="1402" alt="Screenshot 2024-10-08 at 11 43 32" src="https://github.com/user-attachments/assets/0d16a37d-2607-48f1-9051-268d4838b6ed">

the working url is [this](https://docs.gno.land/gno-tooling/cli/gnokey/working-with-key-pairs/#listing-available-keys)

**Comment by leohhhn** [comment]
Thanks for noticing. I fixed it in #2926, but you're always welcome to fix these kinds of issues youself. It can also be a good way to learn about other parts of the codebase.

**Comment by MalekLahbib** [comment]
> Thanks for noticing. I fixed it in #2926, but you're always welcome to fix these kinds of issues youself. It can also be a good way to learn about other parts of the codebase.

I would've done it if I knew where to do it. I searched for it, but maybe not the good way :). I will ask the next time.
