### ISSUE TITLE
02

### ISSUE THREAD

**Issue by loveyou001** [gnolang/gno#2930]
[Subject of the issue]

 Description

Describe your issue in as much detail as possible here

### Your environment

* Go version (example: go1.22.4)
* OS and CPU architecture (example: linux/amd64)
* Gno commit hash causing the issue (example: f24690e7ebf325bffcfaf9e328c3df8e6b21e50c)

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead Logs

Please paste any logs here that demonstrate the issue, if they exist
Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by leohhhn** [comment]
Hey, I assume you opened this by mistake as well. Closing.
