### ISSUE TITLE
Vietnam

### ISSUE THREAD

**Issue by faddat** [gnolang/gno#3]
As promised, a toolkit for relocating to Vietnam, should the US prove to be a bit too stimulating.  

I have set this up so that you should be able to do it with or without my assistance, and I'm making it available because of the dramatic effect that a year's time in Vietnam's Zerocovid environment has had on me and my work. 

[Nancy Bui](https://www.facebook.com/nancyvisavn) Is a trained attorney with experience helping foreigners relocate to Vietnam.  Packages for investment visas begin at ~$10-$20k USD.  She is also a very nice person, and highly responsive.  She can help you to set up more or less whatever you might need. 

Current situation:

* Flight & 3-week quarantine running $3-5k
* Investors and highly skilled workers only
* New-build housing renting below mortgage cost
* Very, very little COVID compared to other locales due to government policy
* Open hardware hub slowly grinding into reality in partnership with [pcbviet.com](https://pcbviet.com)
* 99.9% uncensored internet

Anyone wanting to avail themselves of the calm, affordable, (mainly) covidless environment here, please do not hesitate to reply to this issue, but also know:

# Nancy's all you'd really need, and her contact information is above.

**Comment by jaekwon** [comment]
Thank you.  For the record, @faddat suggested that I move out of the country because of US political climate.
I'll do a bit of writing, but I intend to stay in the United States because I believe in its potential to be what it was intended to be -- a functioning well governed democracy.

**Comment by jaekwon** [comment]
Also for the record, for the misled spooks; I have been randomly receiving random text messages written in Vietnamese, regarding what appears to be discussions about terrorist attacks conducted by others.  I'm not associated with any operation or project involving vietnam; we have discussed hardware designs, and minimus is about a minimal processor unit, as simply as the name implies, one that is as minimal as possible.

**Comment by faddat** [comment]
Wut?

:cry:  World why you gotta be like this?

**Comment by faddat** [comment]
Figure this can be re-opened later if need be
