### ISSUE TITLE
Stop auto-assigning PR reviewers

### ISSUE THREAD

**Issue by Kouteki** [gnolang/gno#3019]
Related to the comment https://github.com/gnolang/gno/issues/1007#issuecomment-2427655633

## Current state

PRs automatically assign teams based on the CODEOWNERS file, as well as 2 core team members (chosen in round robin fashion). As a result, each core team member has 100+ PRs assigned for review.

## Desired state

PR does not have anyone assigned when created. The core team and the review team assign reviewers manually. Each core team member has 2-5 PRs they are expected to review within the next 2 weeks.

To do
- [x] [Remove CODEOWNERS](https://github.com/gnolang/gno/pull/3022)
- [ ] Disable round robin

**Comment by thehowl** [comment]
Whether we have round robin or not, PR reviewers are no longer assigned automatically, so closing.
