### ISSUE TITLE
cmd/gnoland: execBalancesExport leaks the opened file and at no point closes it

### ISSUE THREAD

**Issue by odeke-em** [gnolang/gno#3032]
Reading through this code https://github.com/gnolang/gno/blob/2838ad1a3c3b9795990257cd46f08fc04b2fb3a3/gno.land/cmd/gnoland/genesis_balances_export.go#L29-L78

at no point is the file that's opened per https://github.com/gnolang/gno/blob/2838ad1a3c3b9795990257cd46f08fc04b2fb3a3/gno.land/cmd/gnoland/genesis_balances_export.go#L54
ever closed

**Comment by kristovatlas** [comment]
Thanks for the report, @odeke-em. We're looking into it.

**Comment by odeke-em** [comment]
I've mailed out PR https://github.com/gnolang/gno/pull/3294.
