### ISSUE TITLE
Make `txtar` and Codecov play nice (upload coverage)

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#3085]
## Description

Currently, the monorepo has an abundance of `.txtar` testing suites, but the code they cover is never uploaded or made aware to Codecov, causing the CI to fail on some PRs even though there is coverage.

This task involves making sure code covered with `.txtar` tests (which are ran from `_test.go` files) is visible in Codecov.

DoD:
- CodeCov / go recognizes code ran by `.txtar` tests
- `.txtar` code coverage is visible on the Codecov dashboard

Example PR:
- https://github.com/gnolang/gno/pull/3003

**Comment by gfanton** [comment]
After doing some checks, it appears that the current `txtar` implementation is correctly handling coverage. The only case where `txtar` could skip coverage is when it executes a binary in a separate process, where it loses track of coverage, but this has already been addressed (#1243).

The issue in #3003 is not related to `txtar` but rather to how Go generates coverage by default. See my comment https://github.com/gnolang/gno/pull/3003#discussion_r1833428254.

Closing this for now. Feel free to reopen it if you still think there is a problem related to `txtar` specifically.
