### ISSUE TITLE
[BUG] : CI Codecov

### ISSUE THREAD

**Issue by DIGIX666** [gnolang/gno#3124]
### Description
I push my modification last night on the [PR#2307](https://github.com/gnolang/gno/actions/runs/11827975101/job/32957186324?pr=2307) and all `CI` pass  apart `Codecov`. I receive this error 

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/e30b5902-c8d5-4a28-a3ec-a69f5f25fd3e">

Is this an error in the IC or in the code? 

### Logs
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/2ba7db5b-9c9b-47b1-aa6b-a07b40356424">

**Comment by DIGIX666** [comment]
I think the bug comes from `CODECOV_TOKEN` on [contribs.yml](https://github.com/gnolang/gno/blob/master/.github/workflows/contribs.yml#L30) file

cc @gfanton

**Comment by thehowl** [comment]
This is a global problem on codecov, currently: https://github.com/codecov/codecov-action/issues/1643

**Comment by DIGIX666** [comment]
> This is a global problem on codecov, currently: [codecov/codecov-action#1643](https://github.com/codecov/codecov-action/issues/1643)

Oh ok, thanks for the information :)
