### ISSUE TITLE
[examples] Refactor `r/demo/users`

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno#3131]
## Description

This issue concerns refactoring the `r/demo/users` realm. Improvement areas can be code readability, app rendering, API, etc.

cc @moul - I can tackle this if you agree; just let me know what we should do for the anti-squatting issue.

**Comment by moul** [comment]
-> #2827

**Comment by leohhhn** [comment]
Ah my bad, didn't see it. Will close this now.
