### ISSUE TITLE
quickstart guide typo?

### ISSUE THREAD

**Issue by jsrimr** [gnolang/gno#317]
On [quick_start guide](https://test2.gno.land/r/boards:testboard/5),
```
Acquire testnet tokens using the official faucet.
Go to https://gno.land/faucet
```
the 'https://gno.land/faucet' raises 404 not found error.

I suggest change the url to 'https://test2.gno.land/faucet'

**Comment by tbruyelle** [comment]
To fix this kind of issue, a contributor have to update the gentxs, is it OK for core deveIopers ? Or do you have other plan for gno documentation for test3/mainnet ?

**Comment by moul** [comment]
Yep, anyone is welcome to make PRs against the gentxs/genesis too.

For test3, we will remove the current faucet and switch to a community based one, probably with a discord bot (#364).
