### ISSUE TITLE
chore: shut down test3

### ISSUE THREAD

**Issue by Kouteki** [gnolang/gno#3215]
## Description

Time to shut down the test3 testnet. It served us well.

## Acceptance criteria

- [ ] Take down the [test3 server](https://test3.gno.land/)
- [ ] Take down [Grafana](https://metrics.gno.studio/public-dashboards/fd08a4d67da44d1f903a20432f733235?orgId=1&refresh=10s&from=now-6h&to=now&timezone=browser)

**Comment by sw360cab** [comment]
Summoning @albttx as I don't have the required access to the used provider for that.

**Comment by leohhhn** [comment]
Please ping me when this is completed and I'll remove references from the docs.

**Comment by albttx** [comment]
@leohhhn this is done, you can remove test2 and test3

**Comment by leohhhn** [comment]
https://github.com/gnolang/gno/pull/3259
