### ISSUE TITLE
Making coins (naming)

### ISSUE THREAD

**Issue by matijamarjanovic** [gnolang/gno#3335]
# Issue with Coin Experimentation

Hi, so I experimented with coins and I tried to make a coin named `tony`. This is my code:

```go
package coin

import "std"

func init() {
	Mint()
}

func Mint() string {
    bank := std.GetBanker(std.BankerTypeRealmIssue)
    bank.IssueCoin("g1ej0qca5ptsw9kfr64ey8jvfy9eacga6mpj2z0y", "tony", 100_000_000)
}

func Render(_ string) string {
	bank := std.GetBanker(std.BankerTypeReadonly)
	balance := bank.GetCoins("g1ej0qca5ptsw9kfr64ey8jvfy9eacga6mpj2z0y")

    return balance.String()
}
```

I get this error:

```vbnet
TX HASH:    
--= Error =--
Data: invalid denom, can only issue/remove coins with the realm's prefix: /gno.land/r/matijamarjanovic/coin:
```
This means that this line should look like this:

```go
bank.IssueCoin("g1ej0qca5ptsw9kfr64ey8jvfy9eacga6mpj2z0y", "/gno.land/r/matijamarjanovic/coin:tony", 100_000_000)
```

With this, actually the coin denom results in the pkgpath part being duplicated.

This might need fixing

**Comment by leohhhn** [comment]
@thehowl @MikaelVallenet 

Seems the recent PR introduced a bug with the coin issuing 👀

**Comment by leohhhn** [comment]
Hmm, I tested this on my master branch, and it seems that it's fine 🤷 
Can you check if you have the latest version of Gno?

**Comment by matijamarjanovic** [comment]
> Hmm, I tested this on my master branch, and it seems that it's fine 🤷 
> 
> Can you check if you have the latest version of Gno?
> 
> 

I made sure have the latest version, but since it works for you I will check again later tonight

**Comment by matijamarjanovic** [comment]
> Hmm, I tested this on my master branch, and it seems that it's fine 🤷 Can you check if you have the latest version of Gno?

Actually, when I think about it, looks like there is no bug in the code, this is exactly what is supposed to happen, it's just that I don't see the bigger picture to why this is like it is. Thanks for looking into it

**Comment by MikaelVallenet** [comment]
> @thehowl @MikaelVallenet
> 
> Seems the recent PR introduced a bug with the coin issuing 👀

I don't think it's a bug, we expect a qualified denomination so he should use std.CoinDenom or std.CurrrentRealm().CoinDenom() ... isn't ?
