### ISSUE TITLE
make install  bug

### ISSUE THREAD

**Issue by githublister** [gnolang/gno#387]
make install  
go: downloading golang.org/x/crypto v0.0.0-20220722155217-630584e8d5aa
golang.org/x/crypto v0.0.0-20220722155217-630584e8d5aa  is 404 
![image](https://user-images.githubusercontent.com/20219606/200122127-89d7cbd8-bfff-4c82-bc2a-552661bc4597.png)

**Comment by dhiemaz** [comment]
How does it say when you execute `go get golang.org/x/crypto`?

**Comment by moul** [comment]
looks like a dns error; are you running inside a container or an isolated system maybe?
