### ISSUE TITLE
Improve `gnodev test`

### ISSUE THREAD

**Issue by moul** [gnolang/gno#415]
- [x] 1. `gnodev test --precompile` is not working completely; sometimes it passes where `gnodev precompile && gnodev build` fails.
- [x] 2. `github.com/gnolang/gno/pkgs/gnolang.Precompile` lacks an automatic recursive helper that will also precompile all the imported libraries.

**Comment by harry-hov** [comment]
@moul I think we can close this one. Implemented in #431

**Comment by moul** [comment]
Yep, thank you for the great work.
