### ISSUE TITLE
[repl] preserve state between lines; allow decls. 

### ISSUE THREAD

**Issue by jaekwon** [gnolang/gno#446]
1. Right now the repl doesn't seem to remember any state between lines, so you have to enter all the lines in one go: `var a = 1; print(a);`. 
2. Also, the only lines allowed are statements, but not declarations, so no imports are allowed.

I think we want to fix (1) first, then (2) work on allowing also declarations (if not a statement; order probably significant to prefer Decl over DeclStmt?) interspersed with regular statements; to make the repl actually useful. (also note: SimpleDeclStmt should not be used or modified for this purpose; rather the REPL is doing the work to conform to existing gno code). Then one could type in the repl:
```
> import fmt
> a := "hello"
> fmt.Println(a)
```

That said, the repl doesn't seem to be high priority.

**Comment by moul** [comment]
@mvertes, maybe this challenge can be a good match for you?

**Comment by thehowl** [comment]
This is mostly supported now; there's an outlier with `:=` but #1908 is more specific.

Closing for housekeeping in favor of #1908.
