### ISSUE TITLE
longer doc

### ISSUE THREAD

**Issue by benjiqq** [gnolang/gno#452]
- Like interpreted Go, but more ambitious.
- Completely deterministic, for complete accountability.
- Transactional persistence across data realms.
- Designed for concurrent blockchain smart contracts systems.

this sounds good but would be nice to have a longer markdown somewhere to expand. what does interpreted go mean? what does  Transactional persistence mean? what does Completely deterministic mean? ...

**Comment by sbibek086** [comment]
@benjiqq let me try to share what I know:

Completely deterministic, for complete accountability means:
for old state (may mean accounts' balances or may mean smart contract's state like Allow-Interaction-of-Wallet-To-This-SmartContract, Claim etc in this ie. previous block)
 to arrive to new state (ie. accounts' updated balances or smart contract's new state ie. Allowed, Claimed etc), it must be by only one path, NOT MANY path agreed upon by all validators on consensus. 
 
 Path, referred to, you can think of order of steps to arrive from previous block to new block.

**Comment by thehowl** [comment]
https://docs.gno.land/
