### ISSUE TITLE
[docs] install local testnet / test contracts locally

### ISSUE THREAD

**Issue by moul** [gnolang/gno#478]
We should improve the documentation about how to work locally.
Addresses #408 

---

> Is it possible to install a local testnet to get a proper local development environment?

First, there are multiple ways to interact with Gno:
* using `gnodev` that allows you to use the GnoVM, without a blockchain. this method is super fast and allows you to use development patterns like TDD, where you test your implementation multiple times per minute. _(This is my favorite method)_
* running a `localnet`, by running the `gnoland` command and then configuring our tools like `gnokey` to use `localhost:36657`.
* using the staging network hosted on https://staging.gno.land, reset regularly and where you can use the hardcoded `test` key or use the faucet.
* using the official testnets.

Now, if you prefer to run a full blockchain node instead of just playing with GnoVM, you should play with the `gnoland` binary.
I suggest you run at this video, made by @zivkovicmilos, showing it in practice: https://www.youtube.com/watch?v=-BlnEXCs0eI.
Another old resource may also help you: https://test2.gno.land/r/boards:testboard/5.

---

To people playing Game of Realms. This is an interesting tutorial to write (see #408).

**Comment by leohhhn** [comment]
Closing this issue since we have setup documentation live on the [official docs](https://docs.gno.land).
