### ISSUE TITLE
Official "Getting Started" guide

### ISSUE THREAD

**Issue by moul** [gnolang/gno#499]
We now have more and more good content from the community, mostly linked on the https://github.com/gnolang/awesome-gno repo. We regularly have the same questions.

The next step is to improve the discoverability of the tutorials to allow newcomers to get started quickly.
We should also make it easier to find the answer to an already-replied question.

This issue is to discuss the "how" to achieve this.

### Current ideas:
* updating the `awesome-gno` repo so we can link articles to a specific question, have a spotlight + make an HTML rendering. Then, add a link on this repo's `README.md` file to the "getting started" section of awesome-gno.
* start writing guides on the main repo, in markdown, with PRs, and more reviews (slower, but higher quality).

Part of #408

**Comment by zivkovicmilos** [comment]
Completed as we now have official documentation
