### ISSUE TITLE
Implement GRC1155 for Gnoland

### ISSUE THREAD

**Issue by Jammyaa** [gnolang/gno#521]
Hi, I am a team member of Nebula Labs - a team of blockchain engineers on Cosmos and Ethereum. We have implemented GRC1155 (inspired by ERC1155 on Ethereum) for Gnoland. So anyone from the Gnoland core team can review and approve for this contribution. Thank you very much, we really admire the decentralist vision and will actively contribute to Gnoland.
Our PR: https://github.com/gnolang/gno/pull/520

**Comment by moul** [comment]
Hey @Jammyaa, thank you for your work.

I close this issue so we can discuss it directly on your PR.
We can reopen later if multiple PRs are related to the same topic.

Thank you.
