### ISSUE TITLE
NODEJUMPER - validator participation proposal

### ISSUE THREAD

**Issue by asadovka** [gnolang/gno#538]
We are the Nodejumper.io team - a professional Cosmos Ecosystem validator with 30+ networks portfolio (https://nodejumper.io/)

Your network looks interesting for us, so we want to become a validator & join your Game of Realms activity. Moreover, we are planning to provide contributions to your chain like:

-  On chain analytics
-  Physical node decentralization map
-  Cheat sheet for most popular blockchain commands (validator profile, wallet, token management and etc.)
-  Scripts for secure  server setup (automatic and manual)
-  Scripts for validator node setup  (automatic and manual)
-  Fresh snapshots, live peers and address book
-  Public API endpoints (RPC/ REST/gRPC)

You can check some of them on our website as well.

Let us know if that sounds good to you. Thanks

**Comment by moul** [comment]
@asadovka thank you for your interest, I suggest you look at existing issues and try to contribute.
