### ISSUE TITLE
parsing - struct can have double definitions of value

### ISSUE THREAD

**Issue by albttx** [gnolang/gno#629]
### Description

A struct can have a double definitions of a values

### Your environment

[commit](https://github.com/gnolang/gno/commit/66d5dcc7ffee65240f7aa111a08870034518ccc)

### Steps to reproduce

```go
	osef := struct {
		name string
	}{
		name: "foo",
		name: "bar",
	}
	fmt.Println(osef.name) // bar
```

### Expected behaviour

Syntax error

### Actual behaviour

noting

### Proposed solution

Return a compilation error

**Comment by tbruyelle** [comment]
Interesting :)
