### ISSUE TITLE
CLI parameters to query

### ISSUE THREAD

**Issue by tadvi** [gnolang/gno#636]
## Description

After recent command line refactoring it is unclear how to use `query` to get data from vm module.
Example:

```bash
./gnokey query "vm/qeval" -data "gno.land/r/demo/hello1
Hello()" 
```
Based on `./gnokey query -h` parameters should be: `query [flags] <path>` 

Failing with this:

```bash
./gnokey query "vm/qeval gno.land/r/demo/hello1
Hello()"
```
Looked at handler.go source code but do not see where req.Data is coming from.

It is unusual CLI decision to have mandatory requirement to include \n line feed as part of parameters.

**Comment by tadvi** [comment]
Did recent CLI refactoring broke `gnokey query`?

**Comment by r3v4s** [comment]
could you check last part of this article.

https://onbloc.gitbook.io/gnoland-developer-portal/docs/building-a-realm/realm-examples/hello.gno#3.-the-query-vm-qrender-option-using-gnokey

**Comment by tadvi** [comment]
fixed by pulling most recent version.
