### ISSUE TITLE
avl.Tree Set() in init() function panic when publishing package.

### ISSUE THREAD

**Issue by r3v4s** [gnolang/gno#642]
## avl.Tree Set() panic in init()

![image](https://user-images.githubusercontent.com/104744707/227460423-260a71a8-22ce-4b06-aef8-4357bcf41a43.png)

test case on the right part runs good with `gnodev test`, however actual code on the left can't be published with `gnokey maketx addpkg`.

![image](https://user-images.githubusercontent.com/104744707/227476149-45a291c3-944f-4683-8119-c10e110a6671.png)

funny thing is `avl.Tree Set()` does work in custom func.

If this is limit of `init()` func or intentional, I think gnokey should provide better error handling.
If not, it looks like a bug

**Comment by anarcher** [comment]
I'm not entirely sure, but I think you should create and use `avl.Tree` as `avl.NewTree`. 

```go 
var t avl.Tree

func init() {
  t = avl.NewTree()
  t.Set("foo","bar")
}
```

**Comment by anarcher** [comment]
In a quick test, I feel like that `init()` is called just fine. 

```
START: init
bar true
END: init
CPUCYCLES addpkg 166
.level 1 .msg Executed block [height 86 validTxs 1 invalidTxs 0 [module state]]

```

```go
package main

import "gno.land/p/demo/avl"

var Tree avl.Tree

func init() {
        println("START: init")
        Tree.Set("foo", "bar")
        println(Tree.Get("foo"))
        println("END: init")
}

```

**Comment by r3v4s** [comment]
@anarcher I'm not sure why, but it suddenly works
