### ISSUE TITLE
Help page is broken

### ISSUE THREAD

**Issue by jaekwon** [gnolang/gno#648]
The commands as per https://test3.gno.land/r/demo/boards?help no longer work since the refactor to ff-cli.

**Comment by tbruyelle** [comment]
Yes it's because ffcli requires to have the flags before the arguments (ff stands for *flag first*). The help page has been [fixed][0] but unfortunately not test3.

[0]: https://github.com/gnolang/gno/pull/622

**Comment by thehowl** [comment]
@jaekwon are you happy to close this (and maybe use `staging` for testing things out in a workshop :P) or do you think we should "backport" this to the test3 website?

**Comment by tbruyelle** [comment]
@thehowl the fix concerns only the `website` binary, so maybe we can just release it to test3.

**Comment by moul** [comment]
Let me check if I can just cherry-pick the commit updating the HTML page on test3.

Else, let's plan the next testnet release.

**Comment by moul** [comment]
Fixed on test3.

I released a new version here -> https://github.com/gnolang/gno/releases/tag/chain%2Ftest3.2

Which cherry-picks 66d5dcc7ffee65240f7aa111a08870034518ccc6 and 5582a76f583e6ccc617eb365

![CleanShot 2023-03-28 at 16 34 24](https://user-images.githubusercontent.com/94029/228273452-146e285f-d1c7-478a-86f0-0fb76e5740a4.png)
218bdd5f5786d4bf
