### ISSUE TITLE
New bcrypt parameters make decoding fail for existing account

### ISSUE THREAD

**Issue by grepsuzette** [gnolang/gno#680]
#670 seems to break the decoding with existing passwords.

I just tested `addpkg` with latest master something like:

`gnokey maketx addpkg -deposit=1ugnot -gas-fee=1ugnot -gas-wanted=5000000 -broadcast --pkgpath=examples/r/demo/aaaaaa --broadcast --pkgdir foo mykey`

Gives:
```
Enter password.
ciphertext decryption failed 
```

If I change back `bcryptSecurityParameter = 12` (from 11) and recompile, 
it works.

### Proposed solution

1. Revert the commit. 
2. Maybe we should better understand what exactly what was slow (I think it was Milos who said Account creation was slow, but is it in the context of a test, or for a real registration), 
3. If we really need this, wasn't there a way to store the number of iteration in the password hash with bcrypt? If so, it's an approach, with 12 being the default when none was specified. Or maybe it's a construct (a bit more involved in that case).

**Comment by tbruyelle** [comment]
I confirm the behavior, good catch!

**Comment by moul** [comment]
Revert the PR as suggested in #679? Better idea?

**Comment by thehowl** [comment]
I would say revert the PR, and also fix this behaviour whereby if we change the cost parameter then password comparison doesn't work?

Standard `x/crypto/bcrypt` doesn't have this (the hash, like other compatible hash implementations, use some variation on `$b$cost$salt$hash` IIRC), so that's a good starting point.

**Comment by zivkovicmilos** [comment]
Do we need to preserve backwards compatibility? @moul

**Comment by moul** [comment]
Avoid it when possible, but let's break what makes sense for a few more months.

**Comment by zivkovicmilos** [comment]
> Avoid it when possible, but let's break what makes sense for a few more months.

If we're gonna break this, I suggest we open up the discussion on whether we even need bcrypt (and if so, why a custom implementation) for this sort of thing
