### ISSUE TITLE
tm2/pkg/bft/blockchain: resource leaks from 3 unstopped time.Ticker objects: missing defer .Stop() invocations

### ISSUE THREAD

**Issue by odeke-em** [gnolang/gno#700]
### Description
Found by some of our internal tooling at Orijtech Inc, staticmajor our static analyzer
```shell
/go/src/github.com/gnolang/gno/tm2/pkg/bft/blockchain/reactor.go:211:33: leaking resource
/go/src/github.com/gnolang/gno/tm2/pkg/bft/blockchain/reactor.go:213:43: leaking resource
```

of which if we audit that code, we can clearly see that 3 tickers are created but no .Stop() for any of them and the docs for time.NewTicker clearly say https://pkg.go.dev/time#NewTicker
<img width="1003" alt="Screen Shot 2023-04-04 at 11 07 31 PM" src="https://user-images.githubusercontent.com/4898263/229995126-63bb8c46-dad5-4139-81fb-e30185af2e68.png">

### Proposed solution
Please add a defer and .Stop all 3 tickers
```diff
diff --git a/tm2/pkg/bft/blockchain/reactor.go b/tm2/pkg/bft/blockchain/reactor.go
index 007f7cc..26ab08d 100644
--- a/tm2/pkg/bft/blockchain/reactor.go
+++ b/tm2/pkg/bft/blockchain/reactor.go
@@ -212,6 +212,12 @@ func (bcR *BlockchainReactor) poolRoutine() {
 	statusUpdateTicker := time.NewTicker(statusUpdateIntervalSeconds * time.Second)
 	switchToConsensusTicker := time.NewTicker(switchToConsensusIntervalSeconds * time.Second)
 
+	defer func() {
+		trySyncTicker.Stop()
+		statusUpdateTicker.Stop()
+		switchToConsensusTicker.Stop()
+	}()
+
 	blocksSynced := 0
 
 	chainID := bcR.initialState.ChainID
```

/cc @elias-orijtech

**Comment by thehowl** [comment]
Thank you for your suggestion :)

This is technically true, however:

- The patch you proposed is erroneous, as the tickers are used inside of other goroutines launched from the function. If we were to stop them with defer, the goroutines would still be running (but with stopped, non-working timers).
- ... an alternative would be to finalize them on the return conditions of these goroutines, however...
- in practice, this function is called only once at the startup of a tendermint2 node -- it doesn't have a repeated use, and in practice the tickers just get finalised when the program terminates

So I'll be closing this. On trivial changes like these, please go ahead and do directly a PR, as creating an issue then a PR is more noise than necessary. Thanks again!
