### ISSUE TITLE
Add the deterministic `math/rand` helpers to stdlibs

### ISSUE THREAD

**Issue by moul** [gnolang/gno#744]
Currently, they're only available from `gnovm/tests/imports.go`; we should migrate them to stdlibs, except for `rand.Seed` which sets a global state.

And, list in the PR or in this issue some proofs that those functions are deterministic, like https://github.com/golang/go/blob/e7b04a3e166b47c1591eab13f4a451d939ae8941/src/math/rand/rand.go#L378-L381.

**Comment by thehowl** [comment]
This is done
