### ISSUE TITLE
`go mod tidy` fails

### ISSUE THREAD

**Issue by tbruyelle** [gnolang/gno#749]
Not sure since when, but it is currently failing on `master`.

```
$ go mod tidy
go: finding module for package github.com/gnolang/gno/tm2/pkg/amino/tests/proto3/proto
github.com/gnolang/gno/tm2/pkg/amino/tests/proto3 tested by
	github.com/gnolang/gno/tm2/pkg/amino/tests/proto3.test imports
	github.com/gnolang/gno/tm2/pkg/amino/tests/proto3/proto: no matching versions for query "latest"

$ echo $?
1
```

**Comment by tbruyelle** [comment]
Awesome ty @thehowl it worked after I changed the initial path from `tm2/pkg/amino/tests/proto3/proto` to `tm2/pkg/amino/tests/proto3/`

We should probably add the proto gen to a makefile recipe.

**Comment by thehowl** [comment]
Mhh. I'll reopen this because IMO `go mod tidy` should work without saying or changing anything for all commits on master. I think the question of the issue becomes: do we want to keep the gitignore rule? Do we want to document this somehow? Do we want to add the files back?

**Comment by tbruyelle** [comment]
Good point. As far as I know, most cosmos chains track their `.pb.go` files in VCS, and this is also true for the cosmos-sdk.
The benefit is the code source is complete after the clone, so devs can hack immediately. The downside is the code in `*.pb.go` is large and ugly, which disrupts the code review (when it changes).

For accessibility, I would say we should track them.
