### ISSUE TITLE
Use `jaekwon/testify` or `stretchr/testify`

### ISSUE THREAD

**Issue by tbruyelle** [gnolang/gno#777]
Codebase currently uses both of them, which is confusing because if I'm not wrong the only difference between the 2 is the expected vs actual order in methods.

**Comment by moul** [comment]
Regarding the .go part, I'll defer to @jaekwon.

In my opinion, I feel like I'm missing an equivalent in .gno and feel uncomfortable writing tests without it. Therefore, I propose porting the final choice to Gno and ensuring a fair approach to licensing/copyright (related to issue #679).

**Comment by jaekwon** [comment]
Let's go with the jaekwon one. We can just fork it over to gnolang/testify and use that. 
And yes, porting to gno sounds good too.
Ideally lean too, if reasonable.

**Comment by moul** [comment]
FYI, I started experimenting in Gno with an even simpler API not relying on reflection: https://github.com/gnolang/gno/pull/928.

**Comment by tbruyelle** [comment]
Note that `jaekwon/testify` is not up to date and it's missing some methods like `ErrorIs`
