### ISSUE TITLE
remove `tm2/pkg/crypto/keys/client/migration.go` after test4

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#800]
See #759 

The migration file was added to ease the transition for old users who want to see the changes to Gno after test3 without the gno tools forgetting their keys. It should be removed when deemed proper, and definitely before an hypothetical test5.

**Comment by Villaquiranm** [comment]
Hello @Kouteki @thehowl 
Opened this PR but I'm not sure this is all I need to do. let me know if I can add something else :)
