### ISSUE TITLE
Transaction signature bytes always use an uninitialized timestamp

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#810]
## Description

The signature base for transactions is generated from the `SignDoc` structure, which has a field called `Timestamp` (ISO string).

This `Timestamp` field goes into the transaction signature bytes **uninitialized** (as the default value of `time.Time`: `0001-01-01T00:00:00Z`).
https://github.com/gnolang/gno/blob/0aaee73f63e4400f9c630bde8d8c0dc0352c0c1e/tm2/pkg/std/doc.go#L19-L38

This means that the `Timestamp` for _any_ transaction signature needs to be `0001-01-01T00:00:00Z`, as the actual transaction timestamp is not read at all (doesn't go into `SignDoc`).

Of course, this means that any transaction signature that has a valid timestamp (different from `0001-01-01T00:00:00Z`) **will be considered invalid**, because the `gno` verifier code generates the sign bytes assuming it's the default value

@moul 
I'm not sure if we'd be breaking backwards compatibility by making sure the transaction sign bytes take into account the valid transaction signature timestamp instead of the default value

**Comment by moul** [comment]
Related with https://github.com/gnolang/gno/issues/1511

**Comment by piux2** [comment]
"signature that has a valid timestamp (different from 0001-01-01T00:00:00Z) will be considered invalid, because the gno verifier code generates the sign bytes assuming it's the default value" can you point out the code that could cause the failure?
