### ISSUE TITLE
How is `MaxCycles` set for gno.land?

### ISSUE THREAD

**Issue by schollz** [gnolang/gno#821]
This is not a bug, but a question - I'm wondering how the `MaxCycles` gets set and why it is what it is. It looks like its set to `10M` (https://github.com/gnolang/gno/blob/master/tm2/pkg/sdk/vm/keeper.go#L177), but what is the reasoning for that number? 

Practically speaking, I am running into a `CPU cycle overrun` error by exceeding `MaxCycles` with a pretty simple realm (https://github.com/schollz/gno/tree/bytebeat-works) that generates audio. The realm works for 1 second of audio, but 2 seconds seems to exceed the maximum cycles. The idea for this realm was to make an audio-based nft where the contract itself generates the audio. If this is out-of-bounds of what is considered for Gno, that's okay.

**Comment by ajnavarro** [comment]
@schollz I had been looking into it to make it configurable, and I saw that it is set on several code paths; when adding a package (I think that is not the one you are hitting) and when calling a public Gno function (https://github.com/gnolang/gno/blob/master/tm2/pkg/sdk/vm/keeper.go#L251). There is also a limit when evaluating ABCI queries.

I'll try to add a PR by adding a new config param to allow the change of that limit.

**Comment by schollz** [comment]
Thanks @ajnavarro , having it configurable seems good!
