### ISSUE TITLE
Update board install instructions

### ISSUE THREAD

**Issue by tbruyelle** [gnolang/gno#865]
The current post `r/demo/boards:testboard/5` that is populated by a gentx and [referenced in the home page](https://github.com/gnolang/gno/pull/818/files#r1214140370) has to be updated before test4. Some instructions are not up-to-date.

- `make` instructions refer to the old arborescence
- publish `gno.land/p/demo/avl` and `gno.land/r/demo/boards` while they are already published by gentxs.
- faucet instructions ?

**Comment by jefft0** [comment]
This may be related to merged PR https://github.com/gnolang/gno/pull/1034 which improved the boards getting started guide, and related PRs like https://github.com/gnolang/gno/pull/1049 to update the links to the guide.
