### ISSUE TITLE
self-hosted runner for benchmarks

### ISSUE THREAD

**Issue by ajnavarro** [gnolang/gno#916]
## Description

Until we have a self-hosted runner, all benchmark runs will fail because Github is shutting down the process: https://github.com/gnolang/gno/actions/runs/5320090259/jobs/9633403257

This runner must be stateless (as default runners on GitHub).

CC @albttx

**Comment by albttx** [comment]
Working on that ASAP!

**Comment by moul** [comment]
Iin the meantime should we roll back the PR the new workflows

**Comment by ajnavarro** [comment]
@moul https://github.com/gnolang/gno/pull/917 just in case we want to deactivate the workflow until we have the self-hosted runner.
