### ISSUE TITLE
add std.TestSetTimestamp

### ISSUE THREAD

**Issue by moul** [gnolang/gno#924]
Should allow making the `internal/os.Now()`, used by `time.Now()` dynamic in unit tests.

See https://github.com/gnolang/gno/blob/master/gnovm/stdlibs/stdlibs.go#L106-L130

Cc @n0izn0iz, @zxxma

**Comment by thehowl** [comment]
So in place of #569 ? might make sense

**Comment by thehowl** [comment]
Superseding with https://github.com/gnolang/gno/issues/1165#issuecomment-1747861782
