### ISSUE TITLE
Detect bad gno.mod configuration from CI

### ISSUE THREAD

**Issue by moul** [gnolang/gno#927]
PR #882 introduced a bug (https://github.com/gnolang/gno/pull/882) that went unnoticed until after it was merged. It was fixed with PR #921.

The issue arises from the current cycle detection tool, which is only tested with `./gno.land`, when relevant go files are updated, not when the `./examples` folder is modified in a pull request.

To address this, we should update the `examples.yml` workflow to include cycle checks. In the long term, it would be ideal to develop a `gno lint` tool (https://github.com/gnolang/gno/issues/850) to thoroughly check for cycles in the entire example folder.

**Comment by moul** [comment]
cc @harry-hov, @thehowl

**Comment by thehowl** [comment]
Cycles are now detected, because we test gno.land also for simple changes to examples/. `gno mod tidy` is performed in general, and that should detect bad imports. So, done.
