### ISSUE TITLE
Calling a realm that uses std.PrevRealm() has different behavior in var and init blocks

### ISSUE THREAD

**Issue by n0izn0iz** [gnolang/gno#941]
### Description

Calling a realm that uses `std.PrevRealm` has not the same behavior if called in a realm's `var` block or in the `init` block

### Your environment

* macos: 13.3.1
* go: version go1.20.4 darwin/arm64
* gno: master at d684985f9d146c4b6495508adef57a1ea60ba13a

### Steps to reproduce

- Deploy this realm
```go
package var_prev_realm

import (
	"std"

	"gno.land/r/demo/tests"
)

var (
	varRealm  = tests.GetPrevRealm()
	initRealm std.Realm
)

func init() {
	initRealm = tests.GetPrevRealm()
}

func Render(path string) string {
	s := ""
	s += "Var block realm:\n\nPackage path: " + varRealm.PkgPath() + "\n\nAddress: " + varRealm.Addr().String() + "\n\n"
	s += "Init block realm:\n\nPackage path: " + initRealm.PkgPath() + "\n\nAddress: " + initRealm.Addr().String() + "\n\n"
	return s
}
```
- Inspect render

### Expected behaviour

`tests.GetPrevRealm()` returns the same whether called in `var` or `init` block

### Actual behaviour

![Screenshot 2023-07-01 at 15 59 27](https://github.com/gnolang/gno/assets/7917064/8445fd6f-b873-4e88-9303-ce8ad4dc72bc)

### Additional info

Not sure if this is a bug or intended behavior, would love to know the rationale if this is intended

**Comment by leohhhn** [comment]
Hey @n0izn0iz not sure this is relevant anymore.
With this code:

```go
package mypkg

import (
	"std"

	"gno.land/p/demo/ufmt"
	"gno.land/r/demo/tests"
)

var (
	toplvl  = std.PrevRealm().Addr()
	initlvl std.Address

	toplvltest  = tests.GetPrevRealm().Addr()
	initlvltest std.Address
)

func init() {
	initlvl = std.PrevRealm().Addr()
	initlvltest = tests.GetPrevRealm().Addr()
}

func Render(_ string) string {
	out := ufmt.Sprintf("### prevrealm in this realm (=deployer):\n\ntoplvl: %s\n\n initlvl: %s\n\n", toplvl, initlvl)
	out += ufmt.Sprintf("### prevrealm in tests (=current realm addr):\n\ntoplvl using test: %s\n\n initlvl using test: %s\n\n", toplvltest, initlvltest)

	return out
}
```

We get the following output:
![Screenshot 2024-09-12 at 14 13 45](https://github.com/user-attachments/assets/f0d4bcd6-e139-4e03-bb36-c30b29062a3d)

Possibly this was fixed somewhere in between. Can you see if your issue is still relevant, and close it if it's not?

**Comment by n0izn0iz** [comment]
looks good indeed
