### ISSUE TITLE
Add new content and guidelines to Game of Realms readme 

### ISSUE THREAD

**Issue by michelleellen** [gnolang/gno#943]
## Description

Hey @waymobetta 

Can we add the new website content to the GoR readme? And explain adding a GoR tag to the pull request? 

The worldwide competition to find the best contributors to Gno.land is currently in phase one – for advanced developers only.

Once the necessary tools to start phase two are ready, we’ll open up the competition to newer devs and non-technical contributors.

If you want to stack ATOM rewards and play a key role in the success of Gno.land and web3, read more about Game of Realms or open a [PR](https://github.com/gnolang/gno/) today.

**Comment by waymobetta** [comment]
[Game of Realms](https://github.com/gnolang/game-of-realms) has its own repo- is this is the repo you are wishing to update or are you suggesting a change within the [Gno](https://github.com/gnolang/gno) (current) repo?

**Comment by waymobetta** [comment]
> And explain adding a GoR tag to the pull request?

Currently, there is no label for GoR though there is a milestone. Should we create a specific label for GoR PRs?

**Comment by thehowl** [comment]
@waymobetta yes! just added
