### ISSUE TITLE
CI: cancel previous running jobs

### ISSUE THREAD

**Issue by moul** [gnolang/gno#959]
To optimize the Continuous Integration (CI) process, we can implement the following rules to cancel previously running actions:

- If the branch is "master," never cancel the actions.
- If the branch is not "master," ensure that only one run per active pull request (PR) is allowed.

**Comment by inFocus7** [comment]
I pushed a PR (mentioned above) that should solve this 🤞🏼 We'd probably need to run the workflows & push an empty commit afterward just to be certain it works as expected
